### ISSUE TITLE
Fix lazy-loading on Community image

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-main-2022#102]
The community image is not being lazy-loaded when it should be (both before and after #99). Despite being the correct ID for the uploaded media item, the URL does not match. The correct URL should be `https://wordpress.org/files/2022/08/community-photo-2-q50-scaled.webp`, note `-scaled`. We should not just swap the URL though.

The `-scaled` filename comes from `_wp_maybe_scale_and_rotate_image`. WordPress automatically resizes images that are larger than 2560px in either direction, resulting in a new image `oldname-scaled.webp`. The compression used by this resizing degrades the image, and probably caused the issue in #90.

Ironically, the `-scaled` community image is more than 1.5x the original q50 image. It might also be worth opening a core ticket like [this one for PNGs](https://core.trac.wordpress.org/ticket/48736).

I think we should increase `big_image_size_threshold`, and reupload the community image once more. Also, check that if there is a srcset (it should be automatically added once the URL matches, like the `lazy` attribute), and check that those images are not pixelated.

See #90, #97

**Comment by tellyworth** [comment]
Is 2642px the best size for the original?

Looking at `https://wordpress.org/files/2022/08/community-photo-2.webp` at actual size, I see blocky JPEG artefacts in the photograph. There are no artefacts in the brushstroke effect though. I suspect a lower-resolution, lower quality jpeg was upscaled to 2642 or higher before adding the brushstrokes. Effectively we're wasting bytes faithfully reproducing a somewhat blocky jpeg.

We could probably scale _down_ the webp to a lower resolution matching the original jpeg without losing much or any visible quality (except for the brushstroke effect). I don't know what that resolution is though.

I think you're right about the `big_image_size_threshold` as the immediate solution. It might be worth following up with design about re-creating a new webp if the original photograph exists in a higher quality RAW or jpeg copy.

**Comment by ryelle** [comment]
> Is 2642px the best size for the original?

It's 2642px because the design file is 1320 wide, and this is 2x (I'm not sure where the extra pixel comes from 🤷🏻 ). In any case, we probably want to target a bit larger than the average desktop screen x 2 for high DPI screens. this article from 2011 it says [1201px – 1400px](https://css-tricks.com/screen-resolution-notequalto-browser-window/) was the most popular screen size of visitors to CSS Tricks. Between how old the article is, and potentially different audiences, I don't know if that's useful, but I might even go up to 1400 as the target size, so 2800px wide. Balancing that with file size, of course :)

> It might be worth following up with design about re-creating a new webp if the original photograph exists in a higher quality RAW or jpeg copy.

I _think_ this is the only version of the image we have, we've asked for higher res before and this is what we got. But it sounds like they might try to get a new photo at WCUS.

**Comment by ryelle** [comment]
I've increased the "big image" size in https://github.com/WordPress/wporg-main-2022/commit/b32766fd917e187c1d6afd79e8c4b6e9421bf7bd. The next step is to re-upload the image and replace the URL & ID again. Technically the editor background image also needs re-uploading, but that's not important since it shouldn't be lazy-loaded anyway.
