### ISSUE TITLE
Fix spacing issues on wordpress.org

### ISSUE THREAD

**Issue by critterverse** [WordPress/wporg-main-2022#120]
Some spacing issues seem to have popped up on wp.org in the last 24-48 hours. It looks like some inline styling may be being overridden and/or a spacing variable missing:

![image](https://user-images.githubusercontent.com/77359364/189677350-76001f67-c018-4ed4-8a65-dd5a3eeac465.png)
![image (1)](https://user-images.githubusercontent.com/77359364/189677361-d633b6cf-eb24-4c1e-979b-dcb2c5f85531.png)

**Comment by Otto42** [comment]
Which spacing is wrong? I'm not particularly familiar with the new homepage, and realistically, don't see any problems with the screenshots. 

So, it would help to be very specific.

**Comment by critterverse** [comment]
Items like text, buttons, and sections shouldn't be flush against each other. The correct spacing can be seen in this Figma file for reference: https://www.figma.com/file/WHhRwVc4swYnPKdyVWj3du/Home-%26-Download-Pages?node-id=0%3A1

**Comment by jeffikus** [comment]
For the hero and the Build for yourself areas, the padding seems to be overridden by !important styles coming in from I'm not sure where. For example, on the hero;

`[style*="padding-bottom:120px"] {
    padding-bottom: var(--wp--preset--spacing--80) !important;
}`

That is overriding the inline styles of the #intro div
`padding-top:120px;padding-right:0px;padding-bottom:120px;padding-left:0px`

I'm not sure the history there, but that's what seems to be the cause.

**Comment by adamwoodnz** [comment]
The spacing variable `--wp--preset--spacing--80` is now undefined. It should be coming from the parent theme as defined [here](https://github.com/WordPress/wporg-parent-2021/blob/trunk/source/wp-content/themes/wporg-parent-2021/theme.json#L504) as I understand it

**Comment by adamwoodnz** [comment]
Fixed by reactivating the Gutenberg plugin. We'll put something in place to avoid it happening again.

**Comment by tellyworth** [comment]
Related: https://github.com/WordPress/wporg-parent-2021/issues/45
