### ISSUE TITLE
Block sections with offset background color

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-main-2022#13]
The mockup uses this pattern where a background color is slightly offset from its container. Rather than try to play with margins, we can use a linear gradient with a hard stop — see [this pattern for an example](https://wordpress.org/patterns/pattern/two-images-with-shared-colored-strip/).

<img width="1466" alt="Screen Shot 2022-07-20 at 5 57 16 PM" src="https://user-images.githubusercontent.com/541093/180089620-b1890f20-4d1a-4b20-9ed8-205ac61779ed.png">

We can set up a few predefined gradients with hard stops so they can be used as group backgrounds. [Example from twenty twenty-two,](https://github.com/WordPress/wordpress-develop/blob/a925aabc9cd0c1e29656cb9466ab1f2a6cab7c9d/src/wp-content/themes/twentytwentytwo/theme.json#L90-L109) though these are diagonal.

I think we can safely set up a black/white, white/black, blue/white, and white/blue.

**Comment by adamwoodnz** [comment]
The [latest designs](https://www.figma.com/file/WHhRwVc4swYnPKdyVWj3du/Home-%26-Download-Pages?node-id=753%3A11640) don't show this style anymore so I'll park this but leave it open in case things change again.
