### ISSUE TITLE
Increase quality of the homepage images

### ISSUE THREAD

**Issue by javierarce** [WordPress/wporg-main-2022#139]
The images on the home page are a bit blurry, and it would be great to improve their resolution.

I've already added a new version of the "Powerful and empowering" illustration. In the case of the showcase section, instead of loading one big picture, I think we could use a grid of images. To explore that solution, I've created a temporary page [here](https://wordpress.org/?page_id=12852&preview=true) (the individual images can be found [on this Figma file](https://www.figma.com/file/WHhRwVc4swYnPKdyVWj3du/Home-%26-Download-Pages?node-id=2375%3A22575))

It seems to work fine, except that in the tablet and mobile versions padding is added around the section. Does this approach make sense? Would it be possible to remove that padding?

**Comment by ryelle** [comment]
The grid of images is a good idea. Nesting the group in another full-width group is the workaround that's already used on the homepage, so I updated it on that page and it's working 👍🏻 

I don't see an updated "Powerful and empowering" image when I sync the content, so just make sure you save the update when you swap in the image grid.

**Comment by javierarce** [comment]
Thanks for the help!

I was about to update the homepage with the new grid, but I reverted the change because I noticed that in the preview sometimes the images inside the grid change their height randomly (it happens to me in both Chrome and Firefox).

<img width="1920" alt="Screenshot 2022-10-27 at 11 07 07" src="https://user-images.githubusercontent.com/4933/198242758-72468575-46bd-4790-8f2d-3cd2f84125ad.png">

<img width="1920" alt="Screenshot 2022-10-27 at 11 01 08" src="https://user-images.githubusercontent.com/4933/198242799-c37a5872-456b-4433-9e87-17fe58a03b0a.png">

**Comment by ryelle** [comment]
When I preview the post, it's still the big image - can you update the post with the rows so I can test it? I won't be deployed publicly until I sync & deploy it.

**Comment by javierarce** [comment]
Yes, sorry, the homepage is updated now with the stack of images.

**Comment by ryelle** [comment]
The only strange size issue I'm seeing is [this image](https://i2.wp.com/wordpress.org/files/2022/10/showcase_thumb_b.png?w=880&ssl=1), which has some extra transparency on the left. Did the images change size after you did something (scroll, hover) or was it like that on page load?

Before we deploy this, those images will need alt text. Also, having 10 links to the same content is not really great for keyboard-only or screen reader users, do you think there's another way you could link to the showcase?

**Comment by javierarce** [comment]
> The only strange size issue I'm seeing is [this image](https://i2.wp.com/wordpress.org/files/2022/10/showcase_thumb_b.png?w=880&ssl=1), which has some extra transparency on the left. 

Ok, it's removed.

> Did the images change size after you did something (scroll, hover) or was it like that on page load?

It happens on page load and it's not consistent. Sometimes I see everything perfect, other times it looks bad.

<img width="1918" alt="Screenshot 2022-11-01 at 10 45 01" src="https://user-images.githubusercontent.com/4933/199206121-5ed30681-a2e9-41ae-8849-9c80021e6a4c.png">

Talking about this with other people and doing some tests we suspect it could be due to the width difference of the images, so I'm going to see if I can reproduce the bug locally and if so open an issue in the Gutenberg repo.

> Before we deploy this, those images will need alt text. Also, having 10 links to the same content is not really great for keyboard-only or screen reader users, do you think there's another way you could link to the showcase?

You are right. I've removed the link and added the alt texts. Could we link the whole stack to the Showcase?

**Comment by ryelle** [comment]
> Could we link the whole stack to the Showcase?

I don't think Gutenberg allows that  😕 

I noticed this section was also removed, was that intentional? If it stayed, "Find inspiration" could be the showcase link and then there's less need to link all of the images.

<img width="1260" alt="Screen Shot 2022-11-01 at 10 55 55 AM" src="https://user-images.githubusercontent.com/541093/199263774-179a8f2b-e8da-453d-86d9-4f7a2b84db81.png">

**Comment by javierarce** [comment]
> I noticed this section was also removed, was that intentional? If it stayed, "Find inspiration" could be the showcase link and then there's less need to link all of the images.

Oh, no, I think I removed it accidentally, sorry 😞

**Comment by javierarce** [comment]
I have been investigating this problem again, and I have discovered that the problem could be caused by a plugin (maybe Jetpack or a lazy loading plugin).

I did a test on a local site with three images that have the exact same dimensions:

<img width="878" alt="Screenshot 2022-11-04 at 13 46 04" src="https://user-images.githubusercontent.com/4933/199976158-e1215e9e-1b8e-4fea-b448-36cd9c4e629b.png">

But if I enable Jetpack, I get this:

<img width="893" alt="Screenshot 2022-11-04 at 13 45 59" src="https://user-images.githubusercontent.com/4933/199976281-828377ba-ac92-4206-9a07-97686d17e0ec.png">

Sometimes I only get one image with different dimensions, other times I get two or more, but it happens randomly (in Chrome and Firefox, Safari seems to behave well). I believe this could be due to a plugin because after enabling Jetpack the images are loaded with a `data-recalc-dims` property.

I'm not sure if there's something we can do about it. 

My only idea to close this issue is to try uploading three horizontal images (one per row of thumbnails). I'll try that next.

**Comment by javierarce** [comment]
That seems to work ok, but I'm having difficulty displaying crisp images. The big original image looked better than having three independent ones. Could you please check that, @ryelle? 

In case you need them, the individual images can be exported from [here](https://www.figma.com/file/WHhRwVc4swYnPKdyVWj3du/Home-%26-Download-Pages?node-id=2492%3A21474).

**Comment by ryelle** [comment]
I think there's a slight difference in how the page preview works vs how the real content is loaded. I've synced across the three separate images, and they look pretty good to me (not blurry, and I'm using a high-dpi monitor). They seem much larger though— 1.55MB, 2.18MB, and 1.66MB compared to the previous image which was a compressed webp, 194 KB.

I've deployed the change (since I also needed to deploy another change), but maybe these can still be optimized without loosing the quality.

**Comment by javierarce** [comment]
Oh, I see, once published they look great. It would be great to reduce the size of the images, I'll see if I can reduce the quality a bit.

**Comment by ryelle** [comment]
I optimized the showcase images a bit in https://github.com/WordPress/wporg-main-2022/commit/b8fd77637007fe257b16bab3001cefa8b1d8041c. Those images were the result of a testing different image qualities, and this was the level where the differences in the compressed images are almost unnoticeable. 

I'm going to close out this issue now.
