### ISSUE TITLE
Front page template & `index-wporg.php`

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-main-2022#14]
[The `front-page.php` file explains](https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/themes/pub/wporg-main/front-page.php#L4) that this template not used on `wordpress.org`.

```
NOTE: This isn't actually used, instead the site loads `public_html/index-wporg.php`.
```

Is this still true?

If so, maybe we can use a similar syncing method for this file as we do for syncing the global header & footer to the trac template repo?

**Comment by dd32** [comment]
> Is this still true?

No. This is no longer the case, I've removed the reference from the file, see above.
