### ISSUE TITLE
Homepage: Big CTA text should be Light

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-main-2022#142]
As long as the big type remains with this size, this should be the font weight for this CTA, which will be used in other places in the website.

| Site (Regular) | Mockups (Light) |
| ---- | ---- |
| <img width="1234" alt="Captura de ecrã 2022-10-28, às 11 08 09" src="https://user-images.githubusercontent.com/65220155/198562736-13f445d2-c585-47c5-a2a6-990bc952af9b.png"> | <img width="1318" alt="Captura de ecrã 2022-10-28, às 11 07 46" src="https://user-images.githubusercontent.com/65220155/198562724-39f032a0-f54d-4803-aa5f-fbd5421070ce.png"> |

Also noticed the "Get WordPress now" in the paragraph is not a link on the site. If it's on purpose, maybe we should just remove it as it's redundant?

**Comment by ryelle** [comment]
@beafialho Are you able to fix this in the page itself? that content should be editable.

**Comment by beafialho** [comment]
@ryelle should I edit it in `Main Theme Test 2022`?

**Comment by ryelle** [comment]
No, you can edit the page at https://wordpress.org/ directly - it won't be public until a dev syncs it, but you can view the changes by previewing the page.

**Comment by beafialho** [comment]
I can't seem to edit the site 😕 I probably don't have access

**Comment by ryelle** [comment]
I should have checked, sorry about that – I added you, so you can edit the page now.

Once you've made that section look how you want it to, I can copy any changes back to the pattern itself for other sites.

**Comment by beafialho** [comment]
No problem @ryelle, I was not aware of this editing process. Thank you, I've edited the pattern!

For future changes, even small visual ones, do we need to open up an issue here on GH?

**Comment by ryelle** [comment]
> For future changes, even small visual ones, do we need to open up an issue here on GH?

Yeah, any changes still need an issue because a dev is needed to sync the content before it's live for everyone. So I'll sync this change shortly :)
