### ISSUE TITLE
Add About landing page

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-main-2022#148]
Here's the [design](https://www.figma.com/file/W4jJEYbTBLAeMz5GzU1beL/About-Pages?node-id=1%3A2193&t=wTInpVpaFDxkPWG5-0):

| Desktop | Mobile |
|--------|-------|
| <img alt="About Desktop" src="https://user-images.githubusercontent.com/1017872/212790059-eaf080b0-baae-4feb-87e6-f1b63592712f.png"> | <img alt="About Mobile" src="https://user-images.githubusercontent.com/1017872/212790085-a9a973dd-f246-47ba-b5a1-abb35d59262f.png"> |

This should be done as a template and pattern, similar to [Enterprise](https://github.com/WordPress/wporg-main-2022/pull/157)

**Comment by M1racle04** [comment]
Do you want a landing page like this?  Should I work On this?

**Comment by adamwoodnz** [comment]
> Do you want a landing page like this? Should I work On this?

Thanks for the offer but this is already scheduled with the Meta team :)
