### ISSUE TITLE
Add About page content

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-main-2022#149]
Existing page content needs to be converted to use this design. Most of the work should be doable in the post editor, using styles and blocks that already exist in the theme.

![about-subpages](https://user-images.githubusercontent.com/7200686/202597107-f892d62b-8a76-44e4-b55d-bb2caa6eaf11.png)

**Comment by M1racle04** [comment]
Can i work on this?

**Comment by adamwoodnz** [comment]
> Can i work on this?

Thanks for the offer but this is already scheduled with the Meta team :)
