### ISSUE TITLE
Revise Enterprise Content

### ISSUE THREAD

**Issue by bengreeley** [WordPress/wporg-main-2022#154]
During the redesign of the Enterprise page, @thetinyl made minor updates but found there was an opportunity for a larger overhaul of content. I'm linking to her notes for when the time comes that we should revise the content. https://github.com/WordPress/wporg-main-2022/issues/150#issuecomment-1339771950

**Comment by StevenDufresne** [comment]
Closing this issue since forward moving discussions have happened in #174.
