### ISSUE TITLE
How do we handle assets & environments.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-main-2022#17]
While working on `/gutenberg` in the [wporg-gutenberg repo](https://github.com/WordPress/wporg-gutenberg) I ran into pains moving assets around to all the environments.

Since changes were being made directly in the post content, moving the post content around led to improperly linked image URLs. I was repeatedly updating absolute paths and manually uploading new assets. It wasn't a great workflow.

Any ideas on how to manage assets? Should we have all the images in one place? How would that work with the CDN, etc...

**Comment by dd32** [comment]
> Any ideas on how to manage assets? Should we have all the images in one place? How would that work with the CDN

Most of the existing images are stored in `https://s.w.org/images/home/` and are not actually uploads.

We might be able to stick with that for now, and in the future look at enabling site-uploads to be served via the CDN as well where required.

**Comment by StevenDufresne** [comment]
Silly question, how do they get there?

**Comment by dd32** [comment]
> Silly question, how do they get there?

Not Silly! Just not obvious - that's `wordpress.org/images/home` within SVN, so check `public_html/images` for more surprises :)

**Comment by StevenDufresne** [comment]
So the workflow would be as simple as:

1. Commit image to SVN via sandbox
2. Use external URL in content

**Comment by ryelle** [comment]
> Commit image to SVN via sandbox

Once we have the final images, yeah. While we're still working and trying to figure out what images look good, we can upload to the main-test site and use the staging URL in content (which is how the refresh script works, anyway).

> Use external URL in content

I'm pretty sure all the image blocks work with external images, so this should be fine 👍🏻
