### ISSUE TITLE
Enterprise OS icon artwork is misaligned

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wporg-main-2022#172]
The central linework circle in the OS icon isn't centred within the outer circles:

![Screen Shot 2023-01-20 at 11 10 05 AM](https://user-images.githubusercontent.com/1017872/213573480-5b831800-2f27-498e-a96d-7fa7d450be06.jpg)

This results in the icon feeling a little unbalanced.

Existing:
![Screen Shot 2023-01-20 at 11 10 45 AM](https://user-images.githubusercontent.com/1017872/213573727-02b37a58-d6d1-43a7-9e89-0309881fa3db.jpg)

We should update the artwork in Figma and replace the image.

**Comment by adamwoodnz** [comment]
@panchovm Would you be able to update the artwork in the Figma please?

**Comment by fcoveram** [comment]
Here is a new version of this section, it is based on [this design idea](https://github.com/WordPress/wporg-main-2022/issues/174#issuecomment-1410345253)

![image](https://user-images.githubusercontent.com/895819/215772560-e9240944-9883-401d-a587-d390d70e8c63.png)

---

Here are attached the icons

* [Feature icons i4.zip](https://github.com/WordPress/wporg-main-2022/files/10546755/Feature.icons.i4.zip)

**Comment by adamwoodnz** [comment]
Will be fixed in #174
