### ISSUE TITLE
About sub page design and content changes

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wporg-main-2022#191]
Changes related to any of the About sub pages:

[https://wordpress.org/about-2/requirements-2/](https://href.li/?https://wordpress.org/about-2/requirements-2/)
[https://wordpress.org/about-2/features-2/](https://href.li/?https://wordpress.org/about-2/features-2/)
[https://wordpress.org/about-2/security-2/](https://href.li/?https://wordpress.org/about-2/security-2/)
[https://wordpress.org/about-2/roadmap-2/](https://href.li/?https://wordpress.org/about-2/roadmap-2/)
[https://wordpress.org/about-2/history-2/](https://href.li/?https://wordpress.org/about-2/history-2/)

Tasks in comments below please 🙏

**Comment by marko-srb** [comment]
Hey hey, 

Here's video feedback for ya. I am sure it does help, but keep it on low volume, my voice is grungy for some reason.

https://user-images.githubusercontent.com/111751264/216590607-a6469cca-9ff3-45c4-9d96-1b8b256025b1.mp4

On the serious note, here are the list of items mentioned in the video so you can copy/paste, plus one that I forgot there.

- [ ] width of the content should go full width (as in design, or as in News page
- [ ] we are missing 2 brush strokes on the mobile page
- [ ] section below four freedoms needs alignment issues. _One more thing (the height of these rows seem bigger than in original design, please check this — I forgot to mention it in the video)_
- [ ] that same section should be done in a manner we did it on https://wordpress.org/download/


Do let me know in case you need any other help. And thank you!

**Comment by adamwoodnz** [comment]
> I am sure it does help,

Thanks @marko-srb super helpful! I'll get all this patched up :)
