### ISSUE TITLE
Mobile: Align design for consistency with Download and Hosting

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-main-2022#195]
Even though this page has been implemented recently, I suggest we align it with the [Hosting](https://make.wordpress.org/design/2023/01/30/design-share-jan-16-jan-27/) and [Download](https://wordpress.org/download/) generic template.

This is **not urgent**, I just wanted to open a ticket mentioning this.

[Figma](https://www.figma.com/file/PDjQw357bGPAFygumRsGyW/Mobile?node-id=1%3A2193)

<img width="1037" alt="Captura de ecrã 2023-02-03, às 12 45 07" src="https://user-images.githubusercontent.com/65220155/216606820-ef53589a-4376-4af9-ae71-f084a454fd50.png">

cc: @wordpress/meta-design

**Comment by jasmussen** [comment]
Looks good. Forgot to mention in the Figma that we can omit the adminbar. I think there are only a few pages where that shows up. It's a small detail.

Thanks for keeping your eye on this!

**Comment by beafialho** [comment]
Good point, I added the admin bar to the file.

**Comment by ryelle** [comment]
@WordPress/meta-design I pushed this change directly to production because it seemed straightforward ([see the mobile page here](https://wordpress.org/mobile/)), but if anything needs to be tweaked let me know & we can iterate on it.
