### ISSUE TITLE
About: Retire Testimonials Page

### ISSUE THREAD

**Issue by bengreeley** [WordPress/wporg-main-2022#196]
The [Testimonials](https://wordpress.org/about/testimonials/) page currently exists in the 'About' navigation and homepage, but its content is stale from the 15th anniversary of WordPress. Ideally we'd be able to take the following steps:

* Retire the page by creating a 301 redirect to https://wordpress.org/news/category/community/
* Replace link on homepage to point to https://wordpress.org/news/category/community/
* Replace link in subnavigation to point to https://wordpress.org/news/category/community/

**Comment by adamwoodnz** [comment]
Good call. I can update the sub nav when launching the new About pages. Not sure about the 301 but I can look into it.

**Comment by adamwoodnz** [comment]
In light of this I won't bother creating a new testimonials page template and pattern in the new theme.

**Comment by adamwoodnz** [comment]
Points 1 & 2 are complete. Just the redirect to go.

**Comment by adamwoodnz** [comment]
Redirect committed https://meta.trac.wordpress.org/changeset/12397

**Comment by adamwoodnz** [comment]
Redirect deployed
