### ISSUE TITLE
About pages content and design updates

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wporg-main-2022#202]
Tasks:

- [x] Remove links from Logos page images (the [previous template](https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/themes/pub/wporg-main/page-about-logos.php#L52) didn't have them)
- [x] Update 'Testimonials' link in landing page to say 'People of WordPress' (https://github.com/WordPress/wporg-main-2022/commit/8057482d80c793ab0f7ffab71075818c2be8c522)

**Comment by StevenDufresne** [comment]
Adam, any context behind that list? I think we'll need to have the background on that list to inform work after the soon-to-come designs iteration.

**Comment by adamwoodnz** [comment]
The main feedback items on this issue have been addressed, and it looks like there are [significant design updates being worked on in Figma](https://www.figma.com/file/W4jJEYbTBLAeMz5GzU1beL/About?node-id=1513-28017&t=WZKYiDny97vw93iO-0), so I'm going to close this issue out. We can raise new issues when the new designs are ready.

**Comment by adamwoodnz** [comment]
Reopening to fix 'Remove links from Logos page images' as it seems straightforward.
