### ISSUE TITLE
Only one level of bulleted list is displayed

### ISSUE THREAD

**Issue by bengreeley** [WordPress/wporg-main-2022#211]
It appears only the first level of bulleted (unsorted) lists are being output to the screen. For example, if you go to https://wordpress.org/about/roadmap/, the 'CMS -> APIs:' text should have bullets underneath, but are omitted.

If you edit the page, it's shown as:
<img width="534" alt="Screenshot 2023-02-27 at 12 34 46 PM" src="https://user-images.githubusercontent.com/7133400/221639904-99b75617-8814-48b9-a91a-3815e85fe603.png">

However, this is what it looks like on the front end:
<img width="457" alt="Screenshot 2023-02-27 at 12 35 16 PM" src="https://user-images.githubusercontent.com/7133400/221639992-ad298423-8d00-450b-8aba-26717d379cc9.png">

This doesn't appear to be related to CSS, but rather due to the markup not being output (not seeing it in the source code).

**Comment by adamwoodnz** [comment]
Appears to be a problem with our exporter as [the pattern is missing the block markup](https://github.com/WordPress/wporg-main-2022/blob/trunk/source/wp-content/themes/wporg-main-2022/patterns/roadmap.php#L42). Editor view:

![Screen Shot 2023-02-28 at 9 56 56 AM](https://user-images.githubusercontent.com/1017872/221684019-134115d8-3e28-40f5-9539-735f92c1a6fe.jpg)

**Comment by adamwoodnz** [comment]
The patch to manually add the missing bullet points has been deployed. I'll leave this open however, because we need to fix the root cause in the export parser.

**Comment by bengreeley** [comment]
Thanks, Adam.
