### ISSUE TITLE
About: Looks Weird on Ultra-Wide Resolutions

### ISSUE THREAD

**Issue by bengreeley** [WordPress/wporg-main-2022#213]
Page: https://wordpress.org/about

We received some feedback that the [About](https://wordpress.org/about) page looks strange on ultra-wide resolutions. Let's explore adding a max-width to ensure it looks good at all screen sizes.

**Comment by jasmussen** [comment]
Let's try 1160px max-width (or the closest matching applied on other pages) for the main column, to match the mockup:

<img width="1387" alt="Screenshot 2023-03-15 at 09 32 09" src="https://user-images.githubusercontent.com/1204802/225251746-eeee19de-1abf-4ce5-ad94-030a54d5c7c1.png">

The black separators should extend the full width of the page.

**Comment by bengreeley** [comment]
Thanks @jasmussen ! cc @adamwoodnz
