### ISSUE TITLE
Search: Align every search field across the site for consistency.

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-main-2022#228]
There are currently a variety of search field styles across the site:

<img width="332" alt="Screenshot 2023-03-27 at 11 35 58" src="https://user-images.githubusercontent.com/1204802/227903805-9e54efd4-91dc-40a5-832f-a04b3659acd9.png">
<img width="514" alt="Screenshot 2023-03-27 at 11 36 04" src="https://user-images.githubusercontent.com/1204802/227903815-cfb7a43b-b5bf-446e-9ff9-54dc3719105c.png">
<img width="1110" alt="Screenshot 2023-03-27 at 11 36 37" src="https://user-images.githubusercontent.com/1204802/227903825-7ee894a6-0c28-4f5d-b749-699b52bc3606.png">

<img width="502" alt="Screenshot 2023-03-27 at 11 36 54" src="https://user-images.githubusercontent.com/1204802/227903835-5739ae59-b0d1-4ea0-9820-20ec6ddba45d.png">

We should unify all these to a single style and ruleset:

<img width="387" alt="general search" src="https://user-images.githubusercontent.com/1204802/227906523-5bb41961-d314-41fc-a8cf-2bd8a7188dd2.png">

<img width="387" alt="general search" src="https://user-images.githubusercontent.com/1204802/227906312-025f86e8-e1d9-4cff-bf30-bd1c4f74f0a8.png">

* Charcoal 4 placeholder color
* Charcoal search term color
* 14px Inter, same as breadcrumb font size.
* Always 24x24px icons, never larger or smaller, even on mobile.
* 16px font size on mobile.
* Only show an input border when the background is white, or lighter than a 3:1 contrast.

See also WordPress/wporg-mu-plugins#368, and WordPress/wporg-main-2022#216 for general issues with the Google embedded search.

**Comment by ryelle** [comment]
I've updated the parent theme to provide better search block defaults in this PR: https://github.com/WordPress/wporg-parent-2021/pull/79

The global header search, since it's used on classic themes too, will need a separate PR in wporg-mu-plugins, I'll handle that next.

The search box on /search/ is provided by google's embed, I'll leave the updates there to happen with https://github.com/WordPress/wporg-main-2022/issues/216.

- [x] Update styles in parent theme
- [x] Remove override in documentation child theme
- [x] Remove override in developers child theme
- [x] Update style in global header search

**Comment by jasmussen** [comment]
Thank you!

**Comment by ryelle** [comment]
All the search boxes should be using the same styles now, except for the search page itself, though I did try to tweak that a little in google's style settings (couldn't control very much, just the border & button color).

<img width="1155" alt="Screenshot 2023-04-05 at 11 24 03 AM" src="https://user-images.githubusercontent.com/541093/230128042-c9066817-60a4-4295-bfd6-24285b32d948.png">

I'm going to close this, and if there are specific things to fix still we can follow up.

**Comment by jasmussen** [comment]
@ryelle Thanks for all the work. A few small details:
<img width="510" alt="Screenshot 2023-04-11 at 11 00 54" src="https://user-images.githubusercontent.com/1204802/231111149-9c27c6b4-2636-4bca-b078-b44b4e558fbd.png">

The field should be 40px tall, it's about 37px now.

Perhaps related to the focus style, in general the focus style should have the same radius as the input field, 2px, but of course when it's blue on blue it's inset like this, it should not be 2px. But can you try 1px in that case?

<img width="486" alt="Screenshot 2023-04-11 at 11 03 00" src="https://user-images.githubusercontent.com/1204802/231111385-fce982b0-2823-4d91-bc65-25793cf4cb62.png">
