### ISSUE TITLE
Footer: Reduce gap between homepage CTA and footer

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-main-2022#239]
From #221:

> (Mobile) Footer, in homepage: There’s a tall gap between CTA and footer links that can be a bit more conservative.

This issue is mainly visible on mobile:

<img width="600" alt="Screenshot 2023-03-28 at 12 45 38" src="https://user-images.githubusercontent.com/1204802/228212289-66e29ff8-00bd-4a74-914e-b69893585008.png">

It seems like this could be about half that size on mobile, and may be accomplished with a clamp/vw based height value.

This is not an issue on other subpages at the moment.

**Comment by ryelle** [comment]
There's a spacer in the content there, what if we just remove that? It shrinks the space a little on desktop too, but there's still a good amount of room:

| Before | After |
|---|---|
| ![before-desktop](https://user-images.githubusercontent.com/541093/228277628-c9d4aabc-53e4-49c9-bfd3-95e170ff0673.png) | ![after-desktop](https://user-images.githubusercontent.com/541093/228277625-6cbee371-c17b-4a30-8aee-01e51e9cfd88.png) |
| ![before-small](https://user-images.githubusercontent.com/541093/228277630-5242e8f4-6310-4970-a4cc-1c8afd415b80.png) | ![after-small](https://user-images.githubusercontent.com/541093/228277627-ac8525fe-708e-4262-904e-84791f705df9.png) |

**Comment by jasmussen** [comment]
Looks good to me. As we sync later today we can bring it up once more.
