### ISSUE TITLE
About/Philosophy: Adjust heading sizes

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-main-2022#246]
Filing here as it's a general issue about heading sizes, though at the moment this is most visible on the About subpages. Specifically, the heading sizes on https://wordpress.org/about/philosophy/ are a bit off. While we can do a larger design pass separately, it would be good to address the heading hierarchy with a quick fix in the mean time. Suggestion:

<img width="1322" alt="70-40" src="https://user-images.githubusercontent.com/1204802/228790300-24115183-ae2b-4a62-9d8d-9bb7ef13b9ca.png">

For starters, let's use the full 70px heading sizes for the main headings (same as /news). We also need more visible spacing between the major sections. Currently the the top-margin on headings is 20px, inherited from WordPress. The above mockup shows that chnaged to 50px top margin on headings.

Apply the same across the other subpages, notably Graphics & Logos which has the same spacing issue.

CC: @panchovm in case you have some visual thoughts. The alternative to the 70px major heading would be smaller subheadings.

**Comment by ryelle** [comment]
Don't mind me, just transferred this before checking the page itself. I thought it was about changing the base font sizes, but it looks like the About pages use `has-heading-2-font-size` on the first heading. Changing that will be a content update on all pages, once that is removed, it will fall back to the default h1 size of 70px.

> The above mockup shows that chnaged to 50px top margin on headings.

@jasmussen on Documentation, we have 40px above `h2` and 30px above `h3` ([for example, an article](https://wordpress.org/documentation/article/where-to-find-wordpress-help/)). Do you want to use the same spacing on these About pages, or should this section diverge with 50px above h1-h6?

**Comment by jasmussen** [comment]
Happy to try 40 above h2 and 30 above h3 for consistency, and seems worth it to also update in the other direction if that isn't sufficient. Thanks Kelly.

**Comment by fcoveram** [comment]
Jumping in late. I just checked the links and agree with trying what @jasmussen said.
