### ISSUE TITLE
Remove "Vogue" from homepage logo list, doesn't seem to be wordpress.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-main-2022#254]
**Describe the bug**
We have vogue listed in the homepage logo list, but It doesn't appear to use WordPress.

cc @WordPress/meta-design

**Comment by jasmussen** [comment]
Good catch, and connecting up with #253 just in case we need to rethink that section. I.e. for our recent Enterprise conversation it was discussed linking the logos, and ensuring they are colored on hover. That seems pertinent here as well. 

Before we remove it, it might be worth checking if someone like @eidolonnight has context on how the logo came to be here, in case he was around for the first iterations of the homepage, I don't have any context there myself I'm afraid. In the case of some of these logos, they refer to their press-room blogs, or other sections of their site. I wasn't able to find any such things that looked to be using WordPress, but just looking up the context in case it's there.

If need be we can replace the slot with another logo, perhaps Facebook, which is listed on the Enterprise page. They use it for their pressroom.

**Comment by eidolonnight** [comment]
According to BuiltWith, [Vogue is using WordPress](https://builtwith.com/?https%3a%2f%2fwww.vogue.com%2f), and it is also [listed in the Showcase](https://wordpress.org/showcase/vogue/).

**Comment by StevenDufresne** [comment]
My apologies :) Thanks.
