### ISSUE TITLE
Search: "Relevance" wrapping in Google Search 

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-main-2022#260]
**To Reproduce**
1. Go to [search result](https://wordpress.org/search/something/)
2. Notice the "relevance" label is wrapped.

**Screenshots**

<img width="243" alt="Screenshot 2023-05-03 at 9 10 33 PM" src="https://user-images.githubusercontent.com/1657336/235911967-77af1dbc-c9c6-4752-8046-6873e9f83e3a.png">

**Comment by ryelle** [comment]
Forgot to add the issue to the commit message, but this is fixed in https://github.com/WordPress/wporg-main-2022/commit/0258d25c20a0484a8ebef6097603247700e90d2b
