### ISSUE TITLE
Yoast icon is visible as my profile icon

### ISSUE THREAD

**Issue by nielslange** [WordPress/wporg-main-2022#261]
**Describe the bug**

When searching for my profile, the Yoast icon appears as my profile image in the search results.

**To Reproduce**

1. Go to https://wordpress.org/search/Niels+Lange/
2. See the Yoast icon appearing instead of my profile image

**Expected behavior**

I've never worked for Yoast, neither have I ever used their icon as my profile image. I noticed this problem a few weeks ago, but thought it was a caching issue. Given that it persists, and @StevenDufresne asked me to log this issue, I've reported it.

**Screenshots**

<table>
<tr>
<td valign="top">My profile in the search results:
<br><br>

<img width="851" alt="Screen Shot 2023-05-03 at 19 17 13" src="https://user-images.githubusercontent.com/3323310/235913147-adbfdd2f-bcf6-4a4d-aca1-51b408592f7b.png">
</td>
<td valign="top">My profile page:
<br><br>

<img width="852" alt="Screen Shot 2023-05-03 at 19 17 38" src="https://user-images.githubusercontent.com/3323310/235913220-355f6b43-77f7-4c3b-ac9f-6caaa6cea56e.png">
</td>
</tr>
</table>

**Desktop (please complete the following information):**
 - OS: macOS 12.6
 - Browser: Chrome
 - Version: 113.0.5672.63

**Comment by ryelle** [comment]
I've disabled the thumbnails in the search results view— generally they were unhelpful anyway, with all the support forums using the default image, and the docs results grabbing what seemed to be a random image on the page.

**Comment by nielslange** [comment]
Thanks for taking care of this, @ryelle. 🙏
