### ISSUE TITLE
Experiment: Add WP playground link to `/download`.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-main-2022#268]
## Summary
The [wordpress-playground](https://github.com/WordPress/wordpress-playground) is a very low barrier entry to try WordPress. Let's run an experiment, adding it to the download page to see what traction it gets. The hypothesis being that users who want to "download" WordPress would also benefit from trying it.

**Screenshots**
![screen-shot-2023-06-07-at-00 38 36 (1)](https://github.com/WordPress/wporg-main-2022/assets/1657336/8c572a49-6470-48d2-b068-6533171ef122)

**Comment by marko-srb** [comment]
> Still not sure? Explore the WordPress Playground, a live demo environment right from your browser. Try WordPress
<img width="996" alt="Screen Shot 2023-06-08 at 13 58 16" src="https://github.com/WordPress/wporg-main-2022/assets/111751264/f7c72b0d-097b-4502-b08f-3ee2fcdec542">

Few updates: 
- A new copy from Jonathan Pantani. Without dot in end, and shorter...
- Added an arrow there, so it aligns with below links visually. Although we might omit these in near future
- Added both desktop and mobile version

CC: @jasmussen for visibility

**Comment by StevenDufresne** [comment]
@marko-srb I deployed this change using the default page styles which introduces 2 discrepancies. 

1. The mobile styles
    - Gutenberg doesn't give us this. I could write custom CSS to stack and align.
1. Underlined link
    - Content links are not underlined (see section below), I could write custom CSS.

If you want me to make sure it `100%` aligns with the designs, let me know. 

I'm making a judgement on the tradeoffs but willing to iterate again. 👍

**Comment by StevenDufresne** [comment]
Closing for now. Reopen with tweaks.
