### ISSUE TITLE
Don't use hardcoded current WordPress-version in string

### ISSUE THREAD

**Issue by tobifjellner** [WordPress/wporg-main-2022#283]
**Describe the bug**
As I'm translating the strings for the coming roll-out of new wp-org design to Rosetta, I noted a string that should include current WordPress version as a variable, rather than as hardcoded text:
`This is an archive of every release we've done that we have a record of.<br>None of these are safe to use, except the <strong>latest</strong> in the 6.2 series, which is actively maintained.`

Ref: source/wp-content/themes/wporg-main-2022/patterns/download-releases.php:19

**Additional context**
Whenever a string is slightly changed, it needs to be translated again. In most cases, the previous translation will pop up as a suggestion, so it may be a small task. But having the need to do this for several languages means that this string unnecessarily will fall back to US English every time, until the string gets picked up and corrected.

**Comment by dd32** [comment]
The `[stable_branch]` shortcode exists for this purpose.

I've
- updated the page on w.org
- checked for other pages using it (none found)
- updated pattern files using `yarn build:patterns`
- https://github.com/WordPress/wporg-main-2022/commit/3a0135a254aa50f5614e605e69a380d29052b0cb
