### ISSUE TITLE
Remove or adjust language suggestions on Rosetta sites

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-main-2022#290]
On the main wordpress.org site, there's a block to suggest other languages of WP, which leads to the rosetta sites. If you're already on a rosetta site, the new redesign still shows the suggestion.

For example, on es.wordpress.org, I still get the bar.

> WordPress is also available in [한국어](https://ko.wordpress.org/) 및 [Español](https://es.wordpress.org/).

![Screen Shot 2023-07-25 at 18 09 37](https://github.com/WordPress/wporg-main-2022/assets/541093/1d50eba2-7859-4329-827a-8474205c8ab5)

On the old design, rosetta did not have this banner at all. We could remove it.

Or we could check the requested site and not show the suggestion for the current site. If someone accepts multiple languages, it would show the others. So on es.w.org I could see this instead:

> WordPress is also available in [한국어](https://ko.wordpress.org/).

Related ticket: [Language Guess on homepage uses deprecated GlotPress project](https://meta.trac.wordpress.org/ticket/6599)

**Comment by StevenDufresne** [comment]
> Or we could check the requested site and not show the suggestion for the current site. If someone accepts multiple languages, it would show the others. So on es.w.org I could see this instead:

I would vote for this approach.

**Comment by ryelle** [comment]
I've just deployed an update to the language suggestion script, so that it should not suggest the language for the site you're currently on.
