### ISSUE TITLE
Find support Link URL redirect Issue

### ISSUE THREAD

**Issue by utsavtilava** [WordPress/wporg-main-2022#293]
**Describe the bug**
When I click on "Find support," it should ideally redirect me to the support page. Unfortunately, it is currently redirecting to the documentation link instead.

**To Reproduce**
1. Go to '[WordPress.org.](https://wordpress.org/)'
2. Click on '[Find support](https://wordpress.org/support/)'

**Expected behavior**
Currect redirect : https://wordpress.org/support/
Currently redirect : https://wordpress.org/documentation/

**Scree
![Screenshot 2023-07-27 at 3 48 02 PM](https://github.com/WordPress/wporg-main-2022/assets/45058029/ec95fcca-fe3e-4c21-848d-56d8b8281a8b)
nshots**

**Desktop (please complete the following information):**
 - OS: Mac mini
 - Browser Chrome
 - Version 12.1

**Comment by eidolonnight** [comment]
The current [Support page](https://wordpress.org/support/forums/) needs an update, both structurally and visually. Rather than redirect there, let's keep the destination and change the anchor text to "Search documentation".
