### ISSUE TITLE
Homepage: Dream it section overflows in some languages

### ISSUE THREAD

**Issue by javiercasares** [WordPress/wporg-main-2022#306]
Origin:
https://wordpress.slack.com/archives/C02S78ZAL/p1691584951569959

At the new homepage if the "Dream it, build it" is longer than 250px, it breaks.

**Comment by ryelle** [comment]
Pulling out the screenshots & comment from slack:

>  We are testing some parts of the new design of rosetta sites that we can see in https://wordpress.org/ with our language (catalan) and have found a problem with the section “Dream it, build it”.  This section has a max-width of 520px and the h2 has a font-size of 120px. With this sizes when the text is translated to something a litle bit longer, the text does not fit and overflows lines. Here are two images to see the problem.  We can resolve this tweaking the css in locale, but then, any update would make us lose the changes. So, I ask you if you can think on decrease the h2 size and/or increase the max-widht a little bit, to fit more languages? 

| English | Catalan |
|---|---|
| ![Blog_Tool__Publishing_Platform__and_CMS_–_WordPress_org](https://github.com/WordPress/wporg-main-2022/assets/541093/dbfcdd0a-f0a3-491e-8b02-d92d8294d856) | ![Cursor_y_Blog_Tool__Publishing_Platform__and_CMS_–_WordPress_org](https://github.com/WordPress/wporg-main-2022/assets/541093/0049cecc-494b-403c-8d32-a3afaf0f9d71) |

**Comment by marcarmengou** [comment]
We have wp.org translated since we created this issue, but we can't activate the new theme because of this problem.

**Comment by ryelle** [comment]
I have [a PR here](https://github.com/WordPress/wporg-parent-2021/pull/120) to adjust the heading font sizes for different languages, here's how Catalan would look. What do you think, @marcarmengou ?

| Before | After |
|--------|-------|
| ![home-ca-before](https://github.com/WordPress/wporg-parent-2021/assets/541093/67bb7870-7c99-473b-8257-b7c61124fad0) | ![home-ca-after](https://github.com/WordPress/wporg-parent-2021/assets/541093/acc35ccc-9c3b-44af-9c8e-745ccf94da0b) |

**Comment by javiercasares** [comment]
Great! :) LGTM

**Comment by marcarmengou** [comment]
Great! That solves the main problem with the CTA. The fact that you can request some adjustment, if needed, is also sound good. Thanks :)
