### ISSUE TITLE
HTML entities aren't correctly echo'ed in download counter

### ISSUE THREAD

**Issue by tobifjellner** [WordPress/wporg-main-2022#308]
**Describe the bug**
Some locales' format large numbers differently than US English.

When you load a localized "counter" page, the number is correctly formatted. But as soon as the counter gets updated via a Javascript, it's back to American number format.

See https://meta.trac.wordpress.org/ticket/7195 for more details.

Reported by https://profiles.wordpress.org/raikas/

**Comment by ryelle** [comment]
I'm not seeing it revert to American format, I see the `&nbsp;` characters encoded.

On this page: https://sv.wordpress.org/download/counter/

Initial load is correct, but updates look like this:

![a0UBOuk](https://github.com/WordPress/wporg-main-2022/assets/541093/6cfc5de9-5ec0-4964-9f5f-71680825c834)
(screenshot from the linked ticket)
