### ISSUE TITLE
About: Requirements lists incorrect PHP version for legacy users.

### ISSUE THREAD

**Issue by dd32** [WordPress/wporg-main-2022#309]
As reported in slack by @wojsmol: https://wordpress.slack.com/archives/C02QB8GMM/p1691666039408209

**Describe the bug**
https://wordpress.org/about/requirements/

currently lists:
> Note: If you are in a legacy environment where you only have older PHP or MySQL versions, WordPress also works with PHP 5.6.20+ and MySQL 5.0+

This should be pulling the versions on the page from the constants listed in https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/mu-plugins/pub/servehappy-config.php

We can use a shortcode similar to the existing ones:
https://github.com/WordPress/wporg-main-2022/blob/trunk/source/wp-content/themes/wporg-main-2022/inc/shortcodes.php

**Comment by pkevan** [comment]
Fixed in #325.
