### ISSUE TITLE
Block: Create a News block to show latest posts

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-main-2022#31]
The homepage has a section with 3 latest posts from News. We can't control the RSS feed block to get this exact content, so let's spin up a quick block here.

It should show a configurable number of posts (1-10, default to 3), with title, category, and date. In the future, we might want to configure specific categories to pull from, for now we can just pull the latest.

The "View All" link (in the mockup) will be a link in a paragraph below the block, not part of the block.

![List](https://user-images.githubusercontent.com/541093/181599039-a764a39c-a2d0-42fa-b0df-dcb4d074d502.png)

**Comment by StevenDufresne** [comment]
Looking into this.... Are you suggesting we create a block that uses RSS with our own custom layout or we create a block that makes wordpress queries?

**Comment by ryelle** [comment]
I had planned on a block that uses the REST API from News. All the data we want should be available in the public `view` context.
