### ISSUE TITLE
6.3 page: Credits don't appear on rosetta sites

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-main-2022#316]
<img width="761" alt="Screenshot 2023-08-14 at 11 31 04 AM" src="https://github.com/WordPress/wporg-main-2022/assets/541093/5e5ba5bc-4a4c-457d-82bb-772cf8bd5769">

**To Reproduce**
1. Go to https://sv.wordpress.org/download/releases/6-3/
2. Scroll down to the credits section
3. Open the "see all" dropdown
4. See an unexpanded shortcode

The shortcode needs to be included on rosetta sites too. See [dotorg20748]

**Comment by TeemuSuoranta** [comment]
Can confirm this issue is also at Finnish site at a regular post https://fi.wordpress.org/2023/08/09/lionel/

The shortcode [wpcredits 6.3] remains visible.

**Comment by ryelle** [comment]
The shortcode support has been added to rosetta sites, so `wpcredits` works on the release page and in posts now.
