### ISSUE TITLE
Homepage: "WordPress" can be wrapped to multiple lines

### ISSUE THREAD

**Issue by dd32** [WordPress/wporg-main-2022#320]
Reported in https://meta.trac.wordpress.org/ticket/6953 by @bhaveshd36
**Describe the bug**
For display width between 782px and 1080p (tablet resolution), the "Wordpress" word breaks to a new line.

**To Reproduce**
1. Go to https://wordpress.org/
2. Resize screen until the `See what's new in WordPress` heading wraps.

**Expected behavior**

**Screenshots**

![image](https://github.com/WordPress/wporg-main-2022/assets/767313/f17225ee-b215-467f-bf55-f48c54bfc453)

**Comment by dd32** [comment]
My personal thoughts:
- The breakpoint for the section should be such that the expected minimum width is the width of `WordPress` in that font size
- Less ideal would be a filter to wrap `WordPress` with a `<span style="/* css to not break word*/">WordPress</span>`

**Comment by ryelle** [comment]
This was fixed with https://github.com/WordPress/wporg-parent-2021/commit/5944170202266040843a4c129dba8c07f82eff84

<img width="825" alt="Screenshot 2024-01-18 at 12 50 19 PM" src="https://github.com/WordPress/wporg-main-2022/assets/541093/d6a93bd5-56f1-47a6-b51b-ef4769d8e10a">
