### ISSUE TITLE
About / Requirements possibly outdated since move to PHP 7.0.0

### ISSUE THREAD

**Issue by lsinger** [WordPress/wporg-main-2022#325]
**Describe the bug**
The [Requirements page](https://wordpress.org/about/requirements/) states:

> WordPress also works with PHP 5.6.20+

In July, the minimum PHP version [was moved to 7.0.0](https://github.com/WordPress/wordpress-develop/commit/f7dbb2462ba35362be2ab632f466ba1a4d760282), however. 

**To Reproduce**
1. Go to https://wordpress.org/about/requirements/
2. See the "Note: If you are in a legacy environment" paragraph. 
4. See "WordPress also works with PHP 5.6.20+"

**Expected behavior**
Since [this commit](https://github.com/WordPress/wordpress-develop/commit/f7dbb2462ba35362be2ab632f466ba1a4d760282) I would have expected this to say 7.0.0+.

**Comment by ryelle** [comment]
This could either be updated & synced in the page content, or use this suggestion to create a shortcode like `[recommended_php]` (see #309).

**Comment by courtneyr-dev** [comment]
Related conversations:

- https://wordpress.slack.com/archives/C3D6T7F8Q/p1694277554219859
- https://wordpress.slack.com/archives/C60K3MP2Q/p1694376088269039
- https://wordpress.slack.com/archives/C02QB8GMM/p1696455054563909?thread_ts=1696454952.332029&cid=C02QB8GMM

**Comment by pkevan** [comment]
Added shortcode in #358
