### ISSUE TITLE
Homepage: Showcase CTA Improvement

### ISSUE THREAD

**Issue by marko-srb** [WordPress/wporg-main-2022#327]
Context:
As the launching of Showcase v2 is getting closer, we are envisioning updating a CTA section on the hompage as well, in order to follow the updated content. 

This is a light update suggestion, without major layout changes.

[Here is the Figma link.](https://www.figma.com/file/WHhRwVc4swYnPKdyVWj3du/Home-%26-Download-Pages?type=design&node-id=3348%3A981&mode=design&t=kkBjpUMGcN4lpzGM-1)

Here's a comparative view of live section, next to the suggested changes. These should include:

1. Copy edits (so 'starry elements' of the new showcase are present here, and hopefully inviting)
2. New website selection/screenshots
3. New logos (some of the old ones aren't on WP anymore - Vogue, for example)

![GH issue](https://github.com/WordPress/wporg-main-2022/assets/111751264/ff659ee7-f624-4ae6-b928-49c4c27caae5)

Note. Ideal behavior on the mobile is to hide first row of dots. If not possible, can we hide dot-starry-pattern once the responsive size gets to mobile? 

CC: @thetinyl @jasmussen @ndiego

**Comment by marko-srb** [comment]
There are some title ideas in the file itself. 

@thetinyl would you mind trying something along these lines for the title, and adjusting the paragraph to connect? 

![Copy Inspiration](https://github.com/WordPress/wporg-main-2022/assets/111751264/765b43a9-fe82-4f9a-b84f-6c1db2a750c1)

**Comment by ndiego** [comment]
I think the dot layout should be relatively easy to accomplish. Here is some demo code:

```
<!-- wp:group {"align":"full","style":{"spacing":{"padding":<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"right":"var:preset|spacing|20","left":"var:preset|spacing|20"}}},"backgroundColor":"contrast","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-contrast-background-color has-background" style="padding-right:var(--wp--preset--spacing--20);padding-left:var(--wp--preset--spacing--20)"><!-- wp:cover {"url":"https://cldup.com/o3gBGnbYgL.svg","id":422,"isRepeated":true,"dimRatio":0,"customOverlayColor":"#FFF","minHeight":124,"contentPosition":"top left","align":"wide","style":{"spacing":{"padding":{"top":"0","bottom":"0","left":"0","right":"0"}}},"className":"has-dots","layout":{"type":"constrained"}} -->
<div class="wp-block-cover alignwide is-repeated has-custom-content-position is-position-top-left has-dots" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0;min-height:124px"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-0 has-background-dim" style="background-color:#FFF"></span><div role="img" class="wp-block-cover__image-background wp-image-422 is-repeated" style="background-position:50% 50%;background-image:url(https://cldup.com/o3gBGnbYgL.svg)"></div><div class="wp-block-cover__inner-container"><!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"style":{"color":{"background":"#3858e9"}},"fontSize":"medium"} -->
<div class="wp-block-button has-custom-font-size has-medium-font-size"><a class="wp-block-button__link has-background wp-element-button" style="background-color:#3858e9">Find Inspiration</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:group -->
```

It just needed a custom CSS class on the Cover block. This might need some fine tuning, but I used: 

```
.has-dots .wp-block-cover__image-background {
    background-position: 0 27px !important;
    background-repeat: repeat-x;
}
```

<img width="970" alt="image" src="https://github.com/WordPress/wporg-main-2022/assets/4832319/f30cb8b9-b65f-4306-b46d-c08eee0e8b07">

**Comment by thetinyl** [comment]
Thanks @marko-srb. I've shared my [copy suggestions in Figma](https://www.figma.com/file/WHhRwVc4swYnPKdyVWj3du?node-id=3349:17513&mode=design#584217519). I actually think the current headline (with a conceptual tie-in update) is pretty strong already. 

I have some thoughts around the company logos based on your updated version (this is assuming these are your suggested replacements):

- Sony Music is no longer in the showcase, so we should replace... some options could be: Harvard, NYT Company, TechCrunch
- This is a personal opinion, but do we think it could be worth swapping some of the logos that are really just WP blogs (Spotify, Meta, Microsoft) for companies that are using WP for their whole site? There are a few other brands that are relatively well-known (I think) in different industries that could work: noma, Momofuku, Capgemini, for example. Not saying we should replace all those big tech names, but it feels strange to be leaning on a brand only because their blog is powered by WP.

**Comment by ndiego** [comment]
> I actually think the current headline (with a conceptual tie-in update) is pretty strong already.

I agree. While I like the starry theme in concept/visually, the current headline is straight to the point. The Showcase demonstrates the possibilities that WordPress provides. While we could have a bit more fun with it, I do think the main headline should be super clear.

**Comment by marko-srb** [comment]
@thetinyl 

Thanks for the copy edits and the logo suggestions. 

Copy is ready. Logos selection is a bit tricky thing. When I look at previous solution, there were only famous brands there. Although I get the concept behind 

> swapping some of the logos that are really just WP blogs (Spotify, Meta, Microsoft) for companies that are using WP for their whole site

I don't think adding non-recognizable brand logos there is good. Who'll recognize Noma? Momofuku? And in general, logos are reserved here, and generally as a signal of the logos you can recognize. I think we can swap, but I am not sure those would be the right ones. 

I'll send a suggestion shortly. 

Thank you!

**Comment by marko-srb** [comment]
How about this?

![homepage-showcase-cta-v2](https://github.com/WordPress/wporg-main-2022/assets/111751264/2f633b30-f8a7-4359-bf89-dceced734a2d)


@thetinyl let me know your thoughts about it, with context of my previous comment. 

CC: @jasmussen @ndiego

**Comment by ndiego** [comment]
I defer to @thetinyl on copy, but I think this looks great!

**Comment by thetinyl** [comment]
Looks good with the updated language, thanks!

> I don't think adding non-recognizable brand logos there is good. Who'll recognize Noma? Momofuku? And in general, logos are reserved here, and generally as a signal of the logos you can recognize. I think we can swap, but I am not sure those would be the right ones.

I can definitely see where you're coming from. I'll just add that there are some superstar brands in other industries (I used restaurants/food as an example) that may not be known for everyone, but will be very well known in those industries and anyone who follows them/aspires to be like them. Just thinking about the mandate from Matt about folks seeing themselves in the Showcase. 

I think we're fine with what's there at the moment.

**Comment by ndiego** [comment]
Editor demo (frontend will look like the current layout when synced)
<img width="1518" alt="image" src="https://github.com/WordPress/wporg-main-2022/assets/4832319/43e2f8a7-0961-46be-8320-570193a41d8b">

@marko-srb @thetinyl @eidolonnight @jasmussen In the interest of time, I have updated the logos, copy, and graphics using the current layout. This way, no code changes are required other than the sync to the theme. 

Are you comfortable with this approach? We can then add the dots post-launch.

**Comment by thetinyl** [comment]
Copy-wise, looks good to me. Thanks for doing that!

**Comment by jasmussen** [comment]
Looks good.

**Comment by marko-srb** [comment]
@ndiego 


We have a slight issue with the logos spacing/padding on mobile. 


![mobile logos issue](https://github.com/WordPress/wporg-main-2022/assets/111751264/54087912-bbfd-4c8b-8cae-87e03e3b00be)


Let me know if I should open a separate issue for this. Thanks.

**Comment by ryelle** [comment]
@WordPress/meta-design @thetinyl @ndiego Is there anything else that needs to happen here? It looks like the logo issue above is fixed now:

<img width="440" alt="Screenshot 2024-01-18 at 12 45 36 PM" src="https://github.com/WordPress/wporg-main-2022/assets/541093/7e7cd9d0-ffaf-4357-af7c-eb5c768e8d26">

**Comment by thetinyl** [comment]
The logo adjustment was likely a result of needing to swap Spotify out for something else. 

As far as I'm aware, from a copy/content perspective, nothing more is needed.

**Comment by ndiego** [comment]
Yeah, I think we can close.
