### ISSUE TITLE
x-post: Revise 5ftF page

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/wporg-main-2022#349]
Mika's employer has changed, let's revise the 5ftF page. 
https://github.com/WordPress/Marketing-Team/issues/317

**Comment by ryelle** [comment]
It looks like this is being tracked in https://github.com/WordPress/five-for-the-future/issues/239

@courtneyr-dev Is there another place on WP.org (aside from https://wordpress.org/five-for-the-future/) where this needs to be updated?

**Comment by naokomc** [comment]
@ryelle https://github.com/WordPress/Marketing-Team/issues/317 should be the main place to track. I say it's ok to close this one here.

**Comment by ryelle** [comment]
@naokomc Okay, thanks!
