### ISSUE TITLE
Table icon on the Stats page has disappeared

### ISSUE THREAD

**Issue by desrosj** [WordPress/wporg-main-2022#354]
**Describe the bug**
There used to be an icon to the right of each section header on the stats page that toggled the view from a pie chart to a table of data. I used it as recent as last week (maybe the week before at the latest).

Looking at the source code, the `<a>` tag is still present, the icon is not displaying. If I add text or another visual element to the anchor tag manually, the toggle works and changes the view.

**To Reproduce**
1. View the stats page.

**Expected behavior**
The table icon should show next to each stat header.

**Screenshots**
<img width="938" alt="screenshot_2023-11-17_at_8 50 53___am" src="https://github.com/WordPress/wporg-main-2022/assets/359867/6329558e-1ca2-4bd4-8cac-508bdb01dacc">

I have reproduced this on MacOS in Firefox and Safari. A coworker also experienced this in both Edge and Chrome on Windows 11.

**Comment by adamwoodnz** [comment]
Looks like the dashicons font is no longer being loaded.
