### ISSUE TITLE
Move developer.wordpress.org/playground to wordpress.org/playground

### ISSUE THREAD

**Issue by adamziel** [WordPress/wporg-main-2022#355]
As discussed in https://github.com/WordPress/wordpress-playground/issues/728, a Playground overview page makes a lot more sense under the top-level wordpress.org site. To quote @courtneyr-dev:

> Given the general introductory nature of the content currently at https://developer.wordpress.org/playground,
> When I think of where to find such introductory information,
> Then I expect it to be located at a top-level domain such as https://WordPress.org/Playground,
> And I would appreciate a direct link from the main navigation menu to discover what WordPress Playground is all about easily.

Let's make sure it's available on https://wordpress.org/Playground. Technically that could mean either moving developer.wordpress.org/playground there, or creating a new site and populating it with the same content.

Once that's in place, the next step would be to ship the documentation on the developer.wp.org site. I created a separate issue to track it here: https://github.com/WordPress/wporg-developer/issues/412

@StevenDufresne [suggested](https://github.com/WordPress/wordpress-playground/issues/728#issuecomment-1809314830) opening a ticket here to make that happen.

**Comment by StevenDufresne** [comment]
@adamziel @ @courtneyr-dev

Thinking more about this, how many links are in the wild suggesting `//developer.wordpress.org/playground` is the playground itself? 

How are we going to cater to those users?

**Add something in the docs?**

| https://wordpress.github.io/wordpress-playground/ |
|--------|
| <img width="979" alt="Screenshot 2023-12-12 at 11 56 23 AM" src="https://github.com/WordPress/wporg-main-2022/assets/1657336/d7a327af-ddbc-441f-be44-eda6fe46b819"> |

**Comment by adamziel** [comment]
@StevenDufresne Yes, updating the docs seems like the best way forward. I'll add a note at the top along the lines of:

> Looking for the official Playground website? Go to [wp.org/playground](http://wp.org/playground)

**Comment by adamziel** [comment]
How about this? https://github.com/WordPress/wordpress-playground/pull/866

**Comment by StevenDufresne** [comment]
Done.
