### ISSUE TITLE
How to localize front-end content in a local environment

### ISSUE THREAD

**Issue by t-hamano** [WordPress/wporg-main-2022#362]
This is not a bug report, but I would like to address the localization issue when applying the new version, as suggested in #266.

I was able to build a local environment by following the documentation in this repository. But I don't know how to check the localized content on the frontend. Changing the site language from the dashboard doesn't change anything. If anyone knows how to do this, I would be happy if you could tell me.

**Comment by t-hamano** [comment]
I was able to localize it using the following method. Therefore, I would like to close this issue for now.

- Access https://translate.wordpress.org/projects/meta/wordpress-org/
- Select the language you want to apply to your local environment
- Scroll to the bottom of the page and export the translation file as a `.mo` file
- Rename the downloaded file to `wporg-{locale}.mo`
- Upload the file to `/wp-content/languages/themes` in my local environment

**Comment by ryelle** [comment]
@t-hamano Thanks for the instructions for testing with localized content, [I've added that to the readme.](https://github.com/WordPress/wporg-main-2022#working-on-non-english-sites)
