### ISSUE TITLE
About adding users to the test.wordpress.org

### ISSUE THREAD

**Issue by t-hamano** [WordPress/wporg-main-2022#367]
Hi folks,

I'm Aki and I'm a member of the Japanese community.

I discussed with the members of the Japanese community team what approaches we could take to resolve issue #266, which is an issue about updating the Rosetta site to a new version.

As a way to solve the problem, we would like to be able to write CSS for each locale. we have considered three approaches to this:

1. Submit a PR in this repository that contains CSS that only applies to a specific language ([See this comment](https://github.com/WordPress/wporg-main-2022/issues/266#issuecomment-1807768969))
2. Create a plugin that can write CSS for each locale on the dashboard ([See this comment](https://github.com/WordPress/wporg-main-2022/issues/266#issuecomment-1830072990))
3. Use additional CSS from the customizer or Site Editor

We would like to try the _third_ method as the easiest method, but is it possible to provide access to the test site to Japanese contributors who are interested in this issue?

For example, we would write CSS like the following:

```css
html[lang=ja] body {
   --wp--preset--font-size--heading-cta: 90px;
}
```

However, I also heard that the additional CSS section is currently hidden. If so, we would like to verify whether it is possible to enable 

Thank you!

**Comment by ryelle** [comment]
I'm going to close this issue, as we're going with option 1 for now, which was added in #380. There's some more background in [this comment](https://github.com/WordPress/wporg-main-2022/issues/266#issuecomment-1881803157).

Thanks again for all your input across the issues & PRs!
