### ISSUE TITLE
Heading with a highlight has a yellow background

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-main-2022#37]
Use the "highlight" format in the toolbar dropdown to set a text color. In the editor, this looks fine, but on the frontend it has a yellow background.

<img width="1014" alt="Screen Shot 2022-08-01 at 5 22 00 PM" src="https://user-images.githubusercontent.com/541093/182264415-9e7f5320-9ddd-4d4c-b058-9aa94cfdadea.png">

**Comment by adamwoodnz** [comment]
Interestingly when I configure this in the `parent` theme env, and in my local `main` theme env the `mark` element gets transparent background style automatically when highlighted:

![Screen Shot 2022-08-04 at 5 28 02 PM](https://user-images.githubusercontent.com/1017872/182769812-c4d23894-d7d2-401f-849b-72719b837c4d.jpg)

Not sure what causes the different behaviour in `main-test` site

**Comment by ryelle** [comment]
Something is stripping that inline style out on save, it does exist on the main-test site if you switch to code view in the editor… oddly enough you can set it to `background-color: #f00` or `background-color: transparent` and it works, but for some reason it doesn't like `background-color: rgba(0, 0, 0, 0)`.

WP multisite installs can have some extra content sanitization, I'm sure that's what is happening here and why it doesn't happen on our local envs. Could be worth coming back to later to see if it's an issue upstream for Gutenberg or core.

In any case, your fix works well, thanks!
