### ISSUE TITLE
Update default opengraph thumbnail

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-main-2022#378]
Currently when you paste, for example, https://wordpress.org/download/ as a URL into the block editor, opengraph metadata is fetched in and shown when you click the link:

![Screenshot 2023-12-22 at 15 26 30](https://github.com/WordPress/wporg-main-2022/assets/1204802/cfc8171e-f518-4851-9cd5-eab1b8dba24a)

It appears the image being fetched is on this URL:

https://s.w.org/images/backgrounds/wordpress-bg-medblue.png

Presumably that same image is used across a variety of contexts. Let's update this. We can replace it with this:

<img width="1200" alt="WordPress" src="https://github.com/WordPress/wporg-main-2022/assets/1204802/d4394ed8-9c9e-448d-9ef7-53a84062a9ff">

or this:

<img width="1200" alt="WordPress no dots" src="https://github.com/WordPress/wporg-main-2022/assets/1204802/f1d6d4ce-ee5d-4438-b40e-a570efca9f86">

**Comment by wojsmol** [comment]
The image is taken from `<meta property="og:image" content="https://s.w.org/images/backgrounds/wordpress-bg-medblue.png" />`

**Comment by ryelle** [comment]
I've added this image in https://github.com/WordPress/wordpress.org/commit/31bbe7f59da97a1495ba24b169c2b4c29317cc84.

All pages should use the new image, with the exception of the homepage, which uses this image:

![](https://s.w.org/images/home/wordpress-homepage-ogimage.png)

Shares on twitter use a square format image, not the og:image (except the homepage, which uses the large format embed). If you want to update this too, reopen this issue with the new image.

![](https://s.w.org/images/backgrounds/wordpress-bg-medblue-square.png)

**Comment by jasmussen** [comment]
Thank you for the updates, and thank you for the clarification on the square image. I've made a new one, can I kindly ask you to use this one instead?

<img width="1200" alt="WordPress-1" src="https://github.com/WordPress/wporg-main-2022/assets/1204802/4a07e694-cb3e-4366-8801-69bc72f2d76d">

And for the homepage, for the time being, I think we're better off also using the below one for that one:

<img width="1200" alt="WordPress" src="https://github.com/WordPress/wporg-main-2022/assets/1204802/6f54a081-c1bf-4c4b-bdd6-1b86de57c604">

If and when we get a chance to revisit parts of the homepage, we can reconsider having a dedicated one thumbnail just for that. But for now, we can keep it the same for it. Thank you.

[Figma](https://www.figma.com/file/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?type=design&node-id=2802%3A4883&mode=design&t=Obv7NfPOOhQNcAnK-1).

**Comment by ryelle** [comment]
@jasmussen I ended up grabbing [the dotted image](https://s.w.org/images/home/wordpress-default-ogimage.png) for the new default, not the plain one— do you want to remake the square image?

**Comment by jasmussen** [comment]
Do you mean like so?

<img width="1200" alt="WordPress" src="https://github.com/WordPress/wporg-main-2022/assets/1204802/d1a1e4bb-3ea1-461e-a95a-dd9828565e06">
<img width="1200" alt="WordPress-1" src="https://github.com/WordPress/wporg-main-2022/assets/1204802/978572fa-0648-4964-a091-b24570cae11a">

**Comment by ryelle** [comment]
Yeah, exactly. Thanks!

**Comment by ndiego** [comment]
The dotted version looks great!

**Comment by ryelle** [comment]
Okay, I've updated the square image. I think twitter has the old embed cached, and they don't offer a way to clear that, but the meta on the site appears correct - so probably just need to wait that out.
