### ISSUE TITLE
Add local navigation to the About page

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-main-2022#385]
We have begun introducing local navigation on a number of new site redesigns. [Showcase](https://wordpress.org/showcase/) and the new [Developer Resources](https://developer.wordpress.org/) sites are good examples. 

The [About](https://wordpress.org/about/) page has a number of important sub-pages, but they are very hard to find. You have to scroll to the very bottom of the page to see the links. 

<img width="1814" alt="image" src="https://github.com/WordPress/wporg-main-2022/assets/4832319/9661e456-6865-4772-a0f4-22d06c75921e">

While there may be merit to redesigning the entire page, I propose we take an interim step and simply add local navigation to the About page. It could look something like the local navigation on the [Developer Blog](https://developer.wordpress.org/news/) that features dropdowns for the respective categories.

<img width="1811" alt="image" src="https://github.com/WordPress/wporg-main-2022/assets/4832319/dcc6c1f1-e419-4f1c-aecd-f7ce6a090d77">

It's worth noting that the internal About pages already have this local navigation. 

<img width="1810" alt="image" src="https://github.com/WordPress/wporg-main-2022/assets/4832319/8e50e047-ffb4-4b93-8ce8-acf499731267">

What do you think @fcoveram and @jasmussen?

**Comment by fcoveram** [comment]
One of the improvements proposed in [wporg-mu-plugins#535](https://github.com/WordPress/wporg-mu-plugins/issues/535) for the global navigation is based on the same idea, initially suggested by @ryelle. Here is the video attached in the ticket mention for a quick view.

https://private-user-images.githubusercontent.com/895819/288476854-84b608d7-1f21-4793-8317-72fcf85ee29f.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMjYwMTUsIm5iZiI6MTcwNjAyNTcxNSwicGF0aCI6Ii84OTU4MTkvMjg4NDc2ODU0LTg0YjYwOGQ3LTFmMjEtNDc5My04MzE3LTcyZmNmODVlZTI5Zi5tcDQ_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QxNjAxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNWQ5N2ZkNzY4NTAxNGI5ZWQwOGY2ZGUzZGRlMTkyNGFiYWQzYTVhOTg3YzJhMzQ1MmVlNTRlYWVhNzllOGI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ptT8qdpUWh7r-oOGNJlEH01o_4v_XMo5rnfoJbtnBbQ

I would like us to evaluate the benefits of the proposal and its implementation in case we decide to do it.

**Comment by ryelle** [comment]
There's also some discussion on #255, though that predates the latest global nav + local nav designs that are in place (and should probably be closed in favor of this issue).

I think we could add a local nav bar to `/about/` fairly easily, with a nav menu & dropdowns, since it already works on the Developer Blog.

As far as I can tell, the main change in the above global nav proposal is the breadcrumbs area, but we could leave that iteration for later and just make the nav change on `/about/`.

**Comment by fcoveram** [comment]
That sounds great to me @ryelle

**Comment by courtneyr-dev** [comment]
Iterative improvements are certainly welcome.
