### ISSUE TITLE
Replace "search" brushstroke with new sub-navigation.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-main-2022#386]
We have a new sub-navigation that we use on other newly designed pages.
Can we update this one to use it?

**Screenshots**

| Current | Replace with |
|--------|--------|
| ![wordpress org_search_installing__in=support_forums](https://github.com/WordPress/wporg-main-2022/assets/1657336/6ee4fde8-3542-47b3-9132-86f0b82963e7) | <img  alt="Screenshot 2024-02-02 at 3 23 03 PM" src="https://github.com/WordPress/wporg-main-2022/assets/1657336/c19a3c6a-1324-4222-bd8c-9e42b625b030"> |

**Comment by ryelle** [comment]
I'm going to clear the assignees, so that whoever is actively working on this can pick it up.

Should the brushstroke be removed from the site entirely? It's also used on download subpages, ex https://wordpress.org/download/beta-nightly/

**Comment by StevenDufresne** [comment]
:) Sorry for the assignees. I don't know what I was thinking.

I singled out this page because of direct feedback. 

Can we remove the brushstroke? @WordPress/meta-design. @fcoveram

It doesn't match the rest of the site and feels like a relic of the news design which isn't being ported across the site.

**Comment by jasmussen** [comment]
Yes, we can definitely remove the brush-stroke and go with the basic style.

Can we also remove the Google search? ;) — I know this is separately tracked, but it seems to keep coming up. Instead of waiting for an ES powered replacement, are there alternatives? In many situations, the default WordPress seems as good as this, but with the benefit that we can style the spacing, priority, buttons, styles, etc.

**Comment by ryelle** [comment]
> I singled out this page because of direct feedback.
> It doesn't match the rest of the site and feels like a relic of the news design which isn't being ported across the site.

Seems like a good reason to remove it from Download/* too :) but this issue can stay scoped to search.

>  In many situations, the default WordPress seems as good as this, but with the benefit that we can style the spacing, priority, buttons, styles, etc.

The Google search functions to search the whole network, but default WP search only searches the current site. So if we removed it, `wordpress.org/search` would only search the "main site"— About, Download, and a few other one-off pages. Even if you get there from the global header search box.
