### ISSUE TITLE
Download modal not appearing

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wporg-main-2022#389]
**Describe the bug**
There is supposed to be a modal dialogue shown after clicking the 'Download WordPress {version}' button on the [download page](https://wordpress.org/download/)

**To Reproduce**
1. Go to https://wordpress.org/download/
2. Click on 'Get WordPress 6.4.3'

**Expected behavior**
The browser initiates the zip download, and a modal dialog opens as well.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome

**Comment by Otto42** [comment]
What modal are you talking about? That's just a link to the zip file. And it downloads the zip file.

**Comment by adamwoodnz** [comment]
> What modal are you talking about? That's just a link to the zip file. And it downloads the zip file.

The code for the modal is [here](https://github.com/WordPress/wporg-main-2022/blob/trunk/source/wp-content/themes/wporg-main-2022/src/download/index.js), I'll look into why it isn't being triggered, I expect it to be simple. You can see what it looks like on the [original issue](https://github.com/WordPress/wporg-main-2022/issues/40).
