### ISSUE TITLE
Remove "Edit site" from front end admin bar

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-main-2022#390]
Content should be managed through the page editor, not the site editor. The sync script pulls from page content. If the Site Editor is used, it creates a new custom template & overrides the theme template, breaking the connection to translations/future content updates.

To prevent confusion, I think we should remove the "Edit site" option from the frontend, and only let users hit "Edit page" (could also remove "Customize", I don't think anything is managed there anymore).

<img width="432" alt="Screenshot 2024-02-21 at 4 45 36 PM" src="https://github.com/WordPress/wporg-main-2022/assets/541093/15e97313-1860-41f8-a716-ef4ac9a3d558">

This might also prevent Rosetta sites from attempting to "translate" the page content via the site editor.

I'm on the fence about removing Appearance > Editor from wp-admin, are there any legit reasons for needing to use the site editor?

**Comment by dd32** [comment]
> I'm on the fence about removing Appearance > Editor from wp-admin, are there any legit reasons for needing to use the site editor?

I think it would make sense to remove it for now, and add it back if it turns out to be needed.

**Comment by dd32** [comment]
This also appears to be a problem on Rosetta sites.

Simply removing the links to the Site Editor likely isn't enough, ideally we should prevent it's use entirely.

fr.wordpress.org had customized the front page through the site editor, which caused the translated templates not to be used.
