### ISSUE TITLE
Homepage: Update "Get Started" footer

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-main-2022#405]
The "Get Started" section of the homepage, which is part of the [home.php](https://github.com/WordPress/wporg-main-2022/blob/trunk/source/wp-content/themes/wporg-main-2022/patterns/home.php) pattern and located above the global footer, could use a light aesthetic refresh.

Currently, the "Get Started" background is Blueberry 1 (`--wp--preset--color--blueberry-1`), and the global footer also uses a blueberry variant. This approach is not consistent with the rest of the WordPress.org site, which uses either a dark grey (black) or white. The new [Events](https://events.wordpress.org/) page is the only other section that uses a blueberry footer, but that should probably be changed in a separate issue. 

The following design exploration updates the "Get Started" to Charcoal 2 (`--wp--preset--color--charcoal-2`) and also uses the default global footer variant. Thoughts and feedback welcome including any copy changes that might be warranted here. 

| Current | Exploration |
|-|-|
|<img width="1244" alt="image" src="https://github.com/WordPress/wporg-main-2022/assets/4832319/e903543a-d7fa-4c47-b606-91e7143ebb47">|<img width="1317" alt="image" src="https://github.com/WordPress/wporg-main-2022/assets/4832319/6eb2af25-c754-4deb-8c8e-149b85b7ad76">|

_Note that some of the spacing and font sizes appear slightly different in the exploration, this is just because there is not a 1-1 in Figma. The only change is the background color._

**Comment by ndiego** [comment]
@WordPress/meta-design for feedback.

**Comment by fcoveram** [comment]
I definitely prefer the dark variant. Blueberry has been used as accent to highlight actions and links, or specific areas. Dark has less predominance and behaves more flexible.

**Comment by ndiego** [comment]
Sounds good, I think we can move forward with this minor change in the interest of consistency.
