### ISSUE TITLE
Question: When will Rosetta sites use this theme by default?

### ISSUE THREAD

**Issue by devhaozi** [WordPress/wporg-main-2022#407]
Hello, I am a member of the zh_CN polyglot team, we noticed that [wordpress.org](https://wordpress.org/) has been using this theme for quite a long time.
![图片](https://github.com/WordPress/wporg-main-2022/assets/115467771/a765db0e-80d6-470a-8fcb-49dd645b2560)

However, our rosetta site [cn.wordpress.org](https://cn.wordpress.org/) has not used this theme by default.
![图片](https://github.com/WordPress/wporg-main-2022/assets/115467771/527acf24-76bb-43ad-ae04-90319998b8b6)

Is there any news about using this theme by default?

**Comment by devhaozi** [comment]
After looking around a lot I think I've found the answer, close this issue.

**Comment by tobifjellner** [comment]
For other readers of this issue, If your team has translated the new Rosetta theme, then you can request activation with a comment under https://make.wordpress.org/polyglots/2023/08/09/new-wordpress-org-theme-for-your-rosetta-site/ or by contacting me, "tobifjellner" on Slack.
