### ISSUE TITLE
Landing page: WordPress 6.5 microsite is ready to deploy

### ISSUE THREAD

**Issue by thetinyl** [WordPress/wporg-main-2022#408]
A microsite has been created for the WordPress 6.5 release. It's been created in the Site Editor and is all set. [Here's a preview](https://wordpress.org/?page_id=39082&preview=true).

There are further details about how it was put together in [this tracking issue](https://github.com/WordPress/gutenberg/issues/58577). 

With the release scheduled for April 2, it would be great to have this deployed sometime on April 1 or in the early UTC hours of April 2 (the release party is typically scheduled for 17:00 UTC). 

Happy to answer questions if there are any.

cc: @ryelle

**Comment by ryelle** [comment]
The page has been deployed to https://wordpress.org/download/releases/6-5/ (https://wordpress.org/6-5/ will also work as a URL). Does that look correct? @WordPress/meta-design @thetinyl

**Comment by jasmussen** [comment]
It looks right. Happy to see `6.5` also working.

_Inside_ the editor, it now looks wrong; the full-width column collapsed into a narrow thin column in the center. This _seems_ cosmetic only, since the frontend looks right. But just noting, as it used to be full-width. Anything we should address or is this known/fine?

**Comment by thetinyl** [comment]
@ryelle It looks good to me, too. 

Quick question about the contributor names: I did add the shortcode for 6.5, but am not sure that's been updated yet. Would that dynamically change once the names have been updated in the backend?

**Comment by ryelle** [comment]
> Inside the editor, it now looks wrong […] Anything we should address or is this known/fine?

Doesn't this happen to all the pages? I've tried tracking it down before and IIRC it has to do with the fact that we don't put a content block in the template, so it defaults to the constrained layout. If it is just this page, and the editor works correctly on other pages, let me know and I'll take a look again.

> Quick question about the contributor names: I did add the shortcode for 6.5, but am not sure that's been updated yet. Would that dynamically change once the names have been updated in the backend?

It probably hasn't, I believe updating the credits API is part of the release to make sure they get everyone. Once the API is updated, the shortcode will pull in the correct people 👍🏻

**Comment by thetinyl** [comment]
> Once the API is updated, the shortcode will pull in the correct people 👍🏻

Thanks for confirming @ryelle. Just wanted to be extra, extra sure. 🎉

**Comment by jasmussen** [comment]
> Doesn't this happen to all the pages? I've tried tracking it down before and IIRC it has to do with the fact that we don't put a content block in the template, so it defaults to the constrained layout. If it is just this page, and the editor works correctly on other pages, let me know and I'll take a look again.

The thing is, unless I'm completely misremembering (which is possible), then it used to work fine _on this page too_. 

Looking a bit closer, then the code has the toplevel group block set to full-wide:

```
 <!-- wp:group {"metadata":{"name":"Page"},"align":"full","style":{"spacing":{"blockGap":"0"}},"layout":{"type":"constrained"}} -->
```

and yet the block toolbar for the same group is now missing the alignments dropdown:
![Screenshot 2024-04-02 at 19 22 08](https://github.com/WordPress/wporg-main-2022/assets/1204802/38514bfe-3564-4879-af36-f392d445fdfa)

Is it possible that wide alignments was accidentally turned off on theme.json? Not sure what would make this happen. 

In any case, doesn't seem urgent to figure out so long as the frontend looks right.

**Comment by ryelle** [comment]
> Is it possible that wide alignments was accidentally turned off on theme.json? Not sure what would make this happen.

No, like I said, it's something to do with the template lookup process. I found some other pages that worked & tracked down the issue (the page template `_wp_page_template` meta was not set), and it works in the editor now.

**Comment by jasmussen** [comment]
🚀

**Comment by ryelle** [comment]
I think we're all good on this page now, so I'm going to close this issue. Any future content updates should trigger the automatic PR process.
