### ISSUE TITLE
Export logo images for "inspiration" section

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-main-2022#41]
The logos from this section:

<img width="1220" alt="Screen Shot 2022-08-03 at 1 49 28 PM" src="https://user-images.githubusercontent.com/541093/182675427-ae359346-e20a-42bb-81f5-32cb1c0c12d7.png">

@critterverse @beafialho @javierarce Would one of you be able to export these? I tried exporting from figma but they all came out full-white and different sizes. Ideally they'd all be the same height, so they line up properly, and already the necessary color/opacity. (I also left a note about color contrast in the figma)

**Comment by javierarce** [comment]
Here are [the logos](https://www.figma.com/file/WHhRwVc4swYnPKdyVWj3du/Home-%26-Download-Pages?node-id=1405%3A10427) in SVG format, with the same height, and a better contrast ratio: [logos.zip](https://github.com/WordPress/wporg-main-2022/files/9257704/Logos.zip).

**Comment by ryelle** [comment]
Thanks! I've uploaded these to the staging site.
