### ISSUE TITLE
Homepage: Update the "Dream it, built it" section

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-main-2022#415]
Following the [hero update](https://github.com/WordPress/wporg-main-2022/issues/416), the homepage has two sections that discuss the CMS itself and what you can do with it. These sections do not really convey modern WordPress and use evergreen images/content. There is also no callout to the latest WordPress release. Since we have started implementing microsites for each release ([6.5 example](https://wordpress.org/download/releases/6-5/)), we definitely want to feature that somewhere on the homepage. 

The proposed design features a more streamlined message: "Style, Build, Extend" and includes visuals from the latest release and the latest default theme (TT4). Much of the same content on the existing site is also included in the proposal, just reformatted a bit. 

| Current | Proposed |
|-|-|
|<img width="1243" alt="image" src="https://github.com/WordPress/wporg-main-2022/assets/4832319/502d5281-b368-4c87-92e9-cf8de66926c6">|<img width="1438" alt="image" src="https://github.com/WordPress/wporg-main-2022/assets/4832319/5e97e5c8-478e-4c0c-a662-e24cfed9b19a">|

This approach will require the homepage to be updated more frequently to stay in line with the progress of WordPress, but that is the plan. The homepage should feel fresh and current.

**Comment by jasmussen** [comment]
Nice work! One thing to consider in a followup is to bump the font size of the descriptions up to a regular font size. Especially on mobile, the smaller but otherwise precise font size stands out next to the CTA button:
![Screenshot 2024-04-05 at 11 59 24](https://github.com/WordPress/wporg-main-2022/assets/1204802/faff5c35-f563-4047-b493-28270f6f7bbc)
