### ISSUE TITLE
Homepage: Update the Community and Learn sections

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-main-2022#417]
This is a minor update for the Community and Learn sections of the Homepage. The content remains relatively the same, but the ordering is switched. Community comes first and the primary CTA is to the new Events section of the site. 

Overall the design is simplified and more compact. The dot pattern was also added. This design is being used across WP.org, notably on the [Showcase](https://wordpress.org/showcase/). 

| Current | Proposed |
|-|-|
|<img width="1187" alt="image" src="https://github.com/WordPress/wporg-main-2022/assets/4832319/a2f5dfe0-449a-4926-baa4-e91320c1da67">|<img width="1360" alt="image" src="https://github.com/WordPress/wporg-main-2022/assets/4832319/5e7faf8d-6165-4dcd-868f-61c7123dc010">|

**Comment by jasmussen** [comment]
Looks good! I wonder if we can revisit how the dot separator is composed, we probably can't always have the left and right-most columns of dots line up with the content-width, even if that would've been ideal, and absent that at least one edge should line up as is the case now:

![Screenshot 2024-04-05 at 11 59 14](https://github.com/WordPress/wporg-main-2022/assets/1204802/34343eb6-e17c-43ae-b2f0-cb081494e736)

But we can probably update the resolution of the separator graphic, as on 3x screens it starts to get blurry (or there's something off with the image compression).
