### ISSUE TITLE
Performance: Consider using WebP where applicable.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-main-2022#42]
Relevant: https://make.wordpress.org/core/2021/06/07/wordpress-5-8-adds-webp-support/

**Comment by ryelle** [comment]
I haven't used webp before, so I have some questions. Are there any browser compat concerns? Do you have a program that will convert the images? Assuming it doesn't affect the quality, I don't see why we couldn't use this.

But we'll need to add a filter to enable it for multisite sites.

> If I use WordPress multisite, will all my sites work with WebP images?
>
> No. Multisite stores the file types that users are allowed to upload when a site is created. We are working on improving this in [#53167](https://core.trac.wordpress.org/ticket/53167). In the meantime, to ensure all existing sites on a network allow WebP files, you can use the site_option filter in a network mu-plugin to add webp to the allowed file types for all network sites

**Comment by dd32** [comment]
> But we'll need to add a filter to enable it for multisite sites.

Thankfully we can update these on a per-network basis on WordPress.org, [the main network](https://wordpress.org/wp-admin/network/settings.php#upload_filetypes) and [Make network](https://make.wordpress.org/wp-admin/network/settings.php#upload_filetypes) already have webp.
[Rosetta sites don't](https://global.wordpress.org/wp-admin/network/settings.php#upload_filetypes) (but probably don't need it) although they have a larger range defined as needed by locale teams.

**Comment by adamwoodnz** [comment]
I converted and swapped out the 3 large images in the front page for webp, as Page Speed suggested it as an improvement. I think there might be a slight degradation (the tool I used didn't have any conversion settings) but the originals were huge so I think that's to be expected. Let me know what you think @ryelle. I'll do some browser checks now, but browser support looks pretty solid: https://caniuse.com/webp

**Comment by ryelle** [comment]
Looks okay to me 👍🏻 

Anything else need to happen on this issue, or can we close it?

**Comment by adamwoodnz** [comment]
Not sure, is there any more network config required or are we good @dd32 ?

**Comment by dd32** [comment]
I think we're good to close.

The only concern I can see there being is if we need back-compat support for non-webp-enabled browsers. That's a followup issue if it is determined to be a problem after launch though IMHO.
