### ISSUE TITLE
Homepage: Minor tweaks to improve readability and formatting

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-main-2022#421]
This is a collection of minor updates that should be considered for the next iteration.

### Change the heading for the News section

While the heading "What's happening around WordPress" is nice and descriptive, it causes "More news" to wrap on mobile. Instead, let's update to "Latest WordPress news".

| Current | Proposed |
|-|-|
|![319950031-c8f6e28b-e9ba-4819-95f6-8654ff1638df](https://github.com/WordPress/wporg-main-2022/assets/4832319/0eec84cd-cd5d-415a-a038-d65e087087c3)|![319950696-a77621ea-96ee-4074-9387-627a7b1100fb](https://github.com/WordPress/wporg-main-2022/assets/4832319/39de1d3f-a807-4717-ae5b-c661c196ef7d)|

### Update font size throughout

The latest iteration changed the font size on most descriptions to `small`. In practice, this feels a bit too small. So, let's revert to the `normal` font size.

| Current | Proposed |
|-|-|
|<img width="1395" alt="image" src="https://github.com/WordPress/wporg-main-2022/assets/4832319/5dce579d-ff87-4586-a199-367ad9df4652">|<img width="1436" alt="image" src="https://github.com/WordPress/wporg-main-2022/assets/4832319/d7cbbb5a-f09b-42dc-8a0e-da2a48164e05">|

### Update links styles

The links for the Community and Learn sections were a bit unclear, as pointed out in the [feedback](https://make.wordpress.org/meta/2024/04/04/homepage-updates/#comment-9679) following the launch. Let's update them. 

| Current | Proposed |
|-|-|
|<img width="1332" alt="image" src="https://github.com/WordPress/wporg-main-2022/assets/4832319/d794d0d8-a0fb-4148-91f2-fa7624027368">|<img width="1304" alt="image" src="https://github.com/WordPress/wporg-main-2022/assets/4832319/410ee8a9-f582-475a-89cf-5b91d7933635">|

### Update dots separator image

The image appears a bit grainy on mobile devises. Update with higher-res image.

| Current | Proposed |
|-|-|
|<img width="621" alt="image" src="https://github.com/WordPress/wporg-main-2022/assets/4832319/1d524ef1-30ad-419e-a0a6-196afde34013">|<img width="530" alt="image" src="https://github.com/WordPress/wporg-main-2022/assets/4832319/407d5ccf-a4ff-4ea0-aa0f-4995b2f0301e">|

### Update headings

Visually, nothing needs to change, but some of the "headings", notably "Design, Build, Extend", were not using heading markup. This just needs to be updated while keeping the visual aesthetic the same.

**Comment by jasmussen** [comment]
Looks good! 

While you're editing, I mentioned [here](https://github.com/WordPress/wporg-main-2022/issues/417#issuecomment-2039412073) that the dot separator was a bit lowres. Here's a higher res version:

[dot-sepator.png.zip](https://github.com/WordPress/wporg-main-2022/files/14885966/dot-sepator.png.zip)

**Comment by ndiego** [comment]
Updated the description with the separator.

**Comment by johnstonphilip** [comment]
Just noting that I am unable to navigate the top level navigation with my keyboard. The nav tabs should use something like a [tablist](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tablist_role) role, and arrow keys should be used to navigate from tab to tab, instead of using the `tab` key. That's probably an issue for the core navigation block though.

**Comment by miriamelementor** [comment]
The font size feels especially small on mobile, so I'd suggest paying particular attention to how text appears on mobile even with `normal` font.
