### ISSUE TITLE
Rosetta sites: Heading line height too small for cn.w.org

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-main-2022#424]
Hello, this is the zh_CN polyglot team. We switched to new theme a few days ago. Currently, we mainly find that the spacing of multi-line titles is too small, for example:

[https://cn.wordpress.org/about/](https://cn.wordpress.org/about/):
![image](https://github.com/WordPress/wporg-main-2022/assets/115467771/9526716c-1aa0-41ce-8d92-b270509607db)

[https://wordpress.org/about/](https://wordpress.org/about/):
![image](https://github.com/WordPress/wporg-main-2022/assets/115467771/ee0817a9-d213-4340-a72a-91479db7ad21)

[https://cn.wordpress.org/download/releases/6-5/](https://cn.wordpress.org/download/releases/6-5/):
![image](https://github.com/WordPress/wporg-main-2022/assets/115467771/afd383f8-65e4-467e-9812-b84fb114136b)

[https://wordpress.org/download/releases/6-5/](https://wordpress.org/download/releases/6-5/):
![image](https://github.com/WordPress/wporg-main-2022/assets/115467771/7614bafa-a130-416f-b6fd-84c7b9de960d)

@ryelle Can you help optimize this, just adjust it like japanese?

_Originally posted by @devhaozi in https://github.com/WordPress/wporg-main-2022/issues/266#issuecomment-2039468977_

**Comment by ryelle** [comment]
@devhaozi What line height works best?

| line-height: 1 | line-height: 1.1 | line-height: 1.2 |
|---|---|---|
| ![about-10](https://github.com/WordPress/wporg-main-2022/assets/541093/940ca380-c309-4dc3-a15e-dec9ec9ff101) | ![about-11](https://github.com/WordPress/wporg-main-2022/assets/541093/371297bf-bcf1-4bb0-ac75-2f769fccdebc) | ![about-12](https://github.com/WordPress/wporg-main-2022/assets/541093/9f3d072d-c226-418f-b925-f7858cab62f1) |
| ![release-10](https://github.com/WordPress/wporg-main-2022/assets/541093/4cfaa98e-bdc5-4ebf-baa6-2d6a15102f5f) | ![release-11](https://github.com/WordPress/wporg-main-2022/assets/541093/67ebb94b-1af8-4aaf-8c11-a2d7a1941fe5) | ![release-12](https://github.com/WordPress/wporg-main-2022/assets/541093/8f6a20c4-3386-4a3d-b4fe-d4a674142833) |

Are the line heights on other headings okay? For example, this?

<img width="537" alt="Screenshot 2024-04-05 at 3 28 53 PM" src="https://github.com/WordPress/wporg-main-2022/assets/541093/6443f3d5-162a-4585-9538-b750eda0aab4">

**Comment by devhaozi** [comment]
> What line height works best?

1.2 is better, and then the word spacing needs to be increased a little bit, like the last image.

> Are the line heights on other headings okay?

Yes, they looks okay.

**Comment by nukaga** [comment]
Hello. We are just in the process of adjusting the design of the About page in Japanese as well. I'm thinking 1.2 line spacing is good for Japanese as well.

<img width="1920" alt="About" src="https://github.com/WordPress/wporg-main-2022/assets/3480985/6c5668e9-43d5-44cb-b4d9-696751d8c1f2">

ping @miminari

**Comment by ryelle** [comment]
I've updated this to use `line-height: 1.2` whenever the line height is <1, and the default letter spacing whenever letter spacing is negative, for both cn.wordpress.org and ja.wordpress.org.
