### ISSUE TITLE
Cookie page are having layout issues and is missing translations

### ISSUE THREAD

**Issue by Zodiac1978** [WordPress/wporg-main-2022#429]
While testing, [@timse201](https://profiles.wordpress.org/timse201/) found out that the Cookies page does have some issues:
https://de.wordpress.org/about/privacy/cookies/

The main page on Dotorg seems to live on the old theme:
https://wordpress.org/about/privacy/cookies/

But the translated page on the German Rosetta site is on the new theme and this has some minor issues:

The tables are partially hidden because of the 60px padding on the parent wrapper moves them out of the layout.

Also the page is not translated anymore.

(First reported from @coachbirgit on this [post](https://make.wordpress.org/polyglots/2023/08/09/new-wordpress-org-theme-for-your-rosetta-site/#comment-298928))

**Comment by ryelle** [comment]
The Privacy subpages should all still be using the old theme (https://github.com/WordPress/wporg-main-2022/issues/205), so there's a bug in the script that conditionally loads the new theme.

**Comment by ryelle** [comment]
The theme switcher script has been fixed, this page should use the old theme again.
