### ISSUE TITLE
Guidelines page missing - new design/theme missing for forums pages

### ISSUE THREAD

**Issue by Zodiac1978** [WordPress/wporg-main-2022#430]
Another issue @coachbirgit found is that the guidelines page seems not to exist https://de.wordpress.org/support/guidelines/ – originated from the forums handbook page https://wordpress.org/support/guidelines/ 

Also the whole forums pages are not having the new theme. Is this handled in a different place?

**Comment by ryelle** [comment]
Support is a separate site from the "main" WordPress.org site, so nothing under `/support/` is managed here. That said, the support forums are being updated soon (there should be a make post about it shortly).

> the guidelines page seems not to exist

Has this page existed in the past? I spot-checked a few, and I don't see it on other Rosetta sites. This content is a page, not a translatable template, so you'd manage it in your own Rosetta site's page editor.

I'm going to close this issue, but we can open a new issue about the guidelines page if that is a regression.
