### ISSUE TITLE
Adjustments in the Japanese version

### ISSUE THREAD

**Issue by nukaga** [WordPress/wporg-main-2022#432]
If the Japanese translation is included with the English design, it may look strange and the font size and designations may need to be adjusted.

### New TOP

- Specify font for h1,h2.has-heading-3-font-size (Noto serif jp : Regular)
- If possible, change the design of the Get started section, but if it is impossible to change the design, change the font-size to 70px. 
![スクリーンショット 2024-04-17 10 17 58](https://github.com/WordPress/wporg-main-2022/assets/3480985/b78c8ce6-dd79-442a-bb48-5388b6d9e047)
I want to Japanese below English, and change the font size between English and Japanese. I think it's important for this place to serve as a CTA, so I want the design to look cool, but the font is too big and a bit odd in Japanese.

### About

- Specify the font for h1 (Noto serif jp : semi-bold)
- Specify font for h3 (Noto serif jp : regular)
- Specify font for body text (Noto serif jp : regular)

### News-Single

- Specify font for h1 (Noto serif jp), font size 60px

### Download

- Specify font for h1 and h2 (Noto serif JP)
- Specify font for is-style-features section (Noto sans jp : light)

Design samples in Figma are available here:
https://www.figma.com/file/8gSnRdDBGPmpuuwOfoWM3y/Localization%3A-Japanese?type=design&node-id=1%3A2193&mode=design&t=ah3UI8Cuuav8Fyk2-1

Related Issues:
Update rosetta homepages to new homepage version #266
How to Implement Web fonts for a specific language for a specific locale #427

Could someone please make the above adjustment?

**Comment by t-hamano** [comment]
I think it is necessary to continue discussing whether web fonts can be added in #427, so I would like to first submit a PR regarding points other than fonts (font family, font weight).

> If possible, change the design of the Get started section, but if it is impossible to change the design, change the font-size to 70px.
> I want to Japanese below English, and change the font size between English and Japanese. I think it's important for this place to serve as a CTA, so I want the design to look cool, but the font is too big and a bit odd in Japanese.

What do you all think about this? We will probably need to prepare two "Get started" strings with different translation contexts, and only one will be localized. And if you don't need this subtext in languages other than CJK, we may need to hide it with CSS or pattern PHP files.

**Comment by rocket-martue** [comment]
I will suggest overriding CSS variables such as font family, font size, etc.
This will keep the design of the site consistent and ensure that future pages created will reflect the changes.

**Comment by nukaga** [comment]
Thank you @t-hamano !
> What do you all think about this? We will probably need to prepare two "Get started" strings with different translation contexts, and only one will be localized. And if you don't need this subtext in languages other than CJK, we may need to hide it with CSS or pattern PHP files.

The proposal was only a "hopefully". After thinking it over, I think my proposal was not a good one, because it used English as a decoration (sub-context).
So here I thought it would be better to just change it to 70px.

**Comment by t-hamano** [comment]
> If possible, change the design of the Get started section, but if it is impossible to change the design, change the font-size to 70px.

I considered how a change in font size could be applied and what the impact would be if this change were made.

The title of the "Getting started" section has a font size slug of `heading-cta`. This is defined in [theme.json](https://github.com/WordPress/wporg-parent-2021/blob/57027cba54ac755cb835c64a5b302d64b6c570aa/source/wp-content/themes/wporg-parent-2021/theme.json#L689-L691). This size is `120px`, but was changed to `96px` by the following PR:

https://github.com/WordPress/wporg-parent-2021/pull/120

So, changing the title of the "Getting started" section to `70px` means reducing the value of the `heading-cta` font-size slug from `96px` to `70px`.

This font size slug is used in a variety of places.

With that in mind, would it make sense to change 96px to 70px? Below are pages that use a heading-cta slug, comparing how it looks when changed from 96px to 70px. These are the ones I have looked at, they may be on other pages too.

### Top page

https://ja.wordpress.org/?new-theme=1

| 96px | 70px |
|--------|--------|
| ![image](https://github.com/WordPress/wporg-main-2022/assets/54422211/6d3f10e1-a749-4800-8fa8-0644b6f8dc76)| ![image](https://github.com/WordPress/wporg-main-2022/assets/54422211/a81b6815-75e6-4935-a7b3-144b0b66aed7) | 

### WordPress 6.5

https://ja.wordpress.org/download/releases/6-5/?new-theme=1

| 96px | 70px |
|--------|--------|
| ![image](https://github.com/WordPress/wporg-main-2022/assets/54422211/1a1e2245-5270-4162-9ebf-2982c960cba9) | ![image](https://github.com/WordPress/wporg-main-2022/assets/54422211/df763ad9-cc4a-40ed-bdf5-a498b63206c1) |

### WordPress 6.4

https://ja.wordpress.org/download/releases/6-4/?new-theme=1

| 96px | 70px |
|--------|--------|
| ![image](https://github.com/WordPress/wporg-main-2022/assets/54422211/5211c90f-ea7c-4fe9-a648-efbd3368cdac) | ![image](https://github.com/WordPress/wporg-main-2022/assets/54422211/3549d75c-9089-4ecb-9983-c8873c6bf79f) |

### WordPress 6.3

https://ja.wordpress.org/download/releases/6-3/?new-theme=1

| 96px | 70px |
|--------|--------|
| ![image](https://github.com/WordPress/wporg-main-2022/assets/54422211/7aa484c4-6491-40d2-b685-397f8237c3be) | ![image](https://github.com/WordPress/wporg-main-2022/assets/54422211/80cf5bfe-f6e8-45f4-8115-8ac378ed66c9) |
| ![image](https://github.com/WordPress/wporg-main-2022/assets/54422211/9b6b2281-e9b1-42e4-9fe0-dfd640bac121) | ![image](https://github.com/WordPress/wporg-main-2022/assets/54422211/b17ace87-2823-4396-811d-49d714e51f26) |

**Comment by nukaga** [comment]
Thanks for sharing your insights.
I may not have seen everything, but looking at the designs you presented (especially the same class in WordPress 6.5 and WordPress 6.4), the change from 96px to 70px seemed like a good one.

**Comment by ryelle** [comment]
So to summarize, the requested changes for ja.w.org are:

- Update CTA size from 96px to 70px
- Update headings to Noto Serif JP

For the Noto Serif replacement, would updating the `--wp--custom--heading--typography--font-family` variable work? That should apply to all `h1`, `h2`, etc, unless they've been customized.

Does that sound right? Have I missed anything?

**Comment by t-hamano** [comment]
> For the Noto Serif replacement, would updating the `--wp--custom--heading--typography--font-family` variable work? That should apply to all `h1`, `h2`, etc, unless they've been customized.

The Noto Serif JP font is not a font installed by default on the user's local machine, so a web font must be used.

I think the only problem is that [the font published on Google Fonts](https://fonts.google.com/noto/specimen/Noto+Serif+JP) is too huge in size.

![image](https://github.com/WordPress/wporg-main-2022/assets/54422211/91eb227c-e163-409f-a6a9-3f4f27515146)

This problem is explained in detail in the following issue:

https://github.com/WordPress/wporg-main-2022/issues/427

**Comment by ryelle** [comment]
Yes, I know — I'm also working on https://github.com/WordPress/wporg-main-2022/issues/427, I'll have an update there soon.

Can you confirm that no other style changes are requested, though?

**Comment by ryelle** [comment]
I've deployed the update to the CTA font size, and created a few PRs for updating the font — https://github.com/WordPress/wporg-mu-plugins/pull/630 for adding the file, and https://github.com/WordPress/wporg-main-2022/pull/455 for using it.

**Comment by nukaga** [comment]
Thank you very much!

> - Update CTA size from 96px to 70px
> - Update headings to Noto Serif JP

I think it's fine.
If it gets published and I notice any oddities I'd like to raise another issue to discuss.
@ryelle @t-hamano  Thanks to both of you🙏
