### ISSUE TITLE
New landing page: Connecting influencers to affiliate programs ("Creator Connections")

### ISSUE THREAD

**Issue by thetinyl** [WordPress/wporg-main-2022#433]
### Quick summary

> Affiliate partnership opportunities exist within the WordPress ecosystem but can be hard to find. A new “WordPress Creator Connections” (working title) landing page on WordPress.org could help connect creators to these existing programs. This way, they can share their love of WordPress, make money, and stop pushing their audiences to our competitors.

Find the full context, project scope, and discussion in [the original issue](https://github.com/WordPress/Marketing-Team/issues/357) (posted in the Marketing GitHub repo).

### Notes

- From a layout perspective, this page can follow the simple elegance of the proposed Hosting page redesign ([preview here](https://wordpress.org/hosting-2)). 
- Content for this first iteration is nearly ready and can be found in [this document](https://docs.google.com/document/d/16vgEbZZvwgRcgxbwIJAy9BxCjLs7nWz8SQm3z-mi75c/edit) (drafted by @eidolonnight and @rmartinezduque).

Given the simplicity of the layout and that this page will be in the new .org theme, **we can build a first draft in the Editor** (🎉) and then notify Design and Meta when ready for help fine-tuning.

**Comment by thetinyl** [comment]
I've built a [first draft of this page](https://wordpress.org/?page_id=40405&preview=true) in the Editor. It's very bare bones. If anyone from @WordPress/meta-design is available to add some finesse (does not have to be complex), that would be very much appreciated. 

The [copy is mostly final](https://github.com/WordPress/Marketing-Team/issues/357#issuecomment-2239562934), but any changes that will be made won't affect the layout.

**Comment by marko-srb** [comment]
Here's the proposed design that I am trying to implement in the Editor. 


<img width="1280" alt="Creator Connections" src="https://github.com/user-attachments/assets/aaf69f42-6169-4a98-9d47-ed5fef469622">

—
—
—
Active state for FAQ.
![FAQ Active State](https://github.com/user-attachments/assets/efa2f51e-f82e-414f-8874-2114b74dfe84)

**Comment by marko-srb** [comment]
@ryelle and @ndiego 

While I was trying to do the edits, old theme bugged me from having the section width as I set it in editor. See comparison below.

![editor-issue](https://github.com/user-attachments/assets/2137e3fb-c6c9-4cb5-89ee-658138f0f1c0)


Is there a way to switch this page to a new theme we use for Learn? Other elements in there, like hero section, are also done in manner of blocks we used for refresh. If there's an easy way to switch theme to the new one for this page, I should be able to handle all the further edits and creation of the page. Let me know. 

Thanks!

**Comment by ryelle** [comment]
> Is there a way to switch this page to a new theme we use for Learn?

Do you just mean the new design in general, or are you asking for something in the Learn theme in particular? This is the main site, so it would use the main theme like About, Download, and those subpages.

I've set a temporary page template for now, so that it uses the correct width. It was already using the new theme, new pages just need an extra step for previews to look right.

**Comment by marko-srb** [comment]
Thanks @ryelle !

This works now. What I mean by 'Learn' theme is the following. The 3 sections below are actually used from previous designs we used in new theme, or some old layouts, that are still in use, but polished. 

1. This is a classic Learn/Patterns/Themes cover/hero section, just with the graphics on the right. How do I add such element into my page? 

I tried actually using 'home page cover' pattern for this, but it is merged component when I select it from patterns list, and it doesn't allow me to edit. How would I edit it if I use it?

2. A simple title left/paragraph right is the block we used often. For some reason 'column' block isn't working properly (maybe it's just for me) and I cannot replicate the look. 

3. We have links with lines on Learn footer. Also would like to copy this element. 

—

How can I re-use these elements in my page? Also does the 'column' block work for you? I get error when I use it. See ss below. 

<img width="1042" alt="Screen Shot 2024-08-05 at 13 40 54" src="https://github.com/user-attachments/assets/1985f428-2199-48c3-ab1d-512d257762c4">
—
—
—
Column block issue:
<img width="1221" alt="Screen Shot 2024-08-05 at 14 09 45" src="https://github.com/user-attachments/assets/a5794fd0-3ed5-4723-94c6-509125d3ff34">


Thanks!

**Comment by marko-srb** [comment]
Additional note:

I actually went and copied the hero block from home and paste it. Then I was able to edit it. But as soon as I went for 'block' customization in the right panel the block crashed — same as columns block.

Here's ss:

<img width="1433" alt="Screen Shot 2024-08-05 at 14 17 09" src="https://github.com/user-attachments/assets/b5bb83cb-73f4-4aef-88af-a00863f0b09e">

**Comment by ryelle** [comment]
There are block styles you can use to get some of these effects, but we don't use reusable blocks/synced patterns because they're not translatable with the current system.

Copying from other pages is probably the best approach if you don't want to build from scratch. There are probably multiple ways to get 1, cover block or columns. For 2, that's just columns, a heading, and a list block. Same with 3, just the list there has the "links" style to get the borders. Although, if 3 is expandable we do not have an existing style for that, and it might require dev work.

> I actually went and copied the hero block from home and paste it. Then I was able to edit it. But as soon as I went for 'block' customization in the right panel the block crashed — same as columns block.

Yes, I'm seeing this too on all blocks, I'll take a look today.

**Comment by ryelle** [comment]
I've identified the block crashing issue as a bug in Gutenberg, [reported it](https://github.com/WordPress/gutenberg/issues/64270), and rolled back w.org to 18.8 — so you shouldn't have that problem anymore.

**Comment by marko-srb** [comment]
Thanks @ryelle! I'll ping in case I need any access for reusing some blocks in the future.

**Comment by marko-srb** [comment]
<img width="1676" alt="Screen Shot 2024-08-06 at 13 41 37" src="https://github.com/user-attachments/assets/d0ca5b03-cead-4cfa-90f9-ced642bd1732">


@ryelle 

it seems that column block is still crashing whenever I go to 'block' tab to style it. I did multiple tests before I wrote this msg... Let me know if I can do anything to report it somewhere else...

**Comment by marko-srb** [comment]
Ok, column block started working today.

[Here's the draft preview.](https://wordpress.org/?page_id=40405&preview=true)

@ryelle, @ndiego 
I have the following issues present, plus help needed:

1. Hero section. In the Editor, hero graphics goes through the edge of the screen, while it isn't replicated in the preview. I removed the margins, so this may be a bug, or I am not doing something right...

<img width="1434" alt="Screen Shot 2024-08-07 at 15 51 40" src="https://github.com/user-attachments/assets/d256795a-2a0b-4b49-babd-bcbbce08feac">

2. Alignment of right blocks under columns. In all three sections I have right column blocks nicely aligned (in the Editor), while on the preview they are not aligned. Can you help/let me know how to fix this?

<img width="846" alt="Screen Shot 2024-08-07 at 15 52 55" src="https://github.com/user-attachments/assets/6f3782e7-eba2-4c1a-af86-2a451d325942">


2b. Lines are half deleted in this section on the live preview.
<img width="669" alt="Screen Shot 2024-08-07 at 15 55 22" src="https://github.com/user-attachments/assets/7c3f12b2-55d8-455b-8094-cb83636606a0">


3. Can we have Global nav and footer in the same Charcoal 2 color, as in design? I am not really sure how to do this, so if you can help I'd appreciate. Thanks a lot!


I think once we are able to solve these, there are a very few minor copy updates needed and we should be set to go live...

CC: @thetinyl , @eidolonnight

**Comment by marko-srb** [comment]
Ok, I've managed to fix all the issues, except the line breaking 2b thing.

Thanks for the help @ndiego , @ryelle

**Comment by ndiego** [comment]
I fixed 2b. The default separator style in the Editor looks full width, when it actually isn't on the frontend. I switched the style to "Wide Line". 

<img width="308" alt="image" src="https://github.com/user-attachments/assets/90f21404-eee3-41b6-9cc8-2580bede21cf">

**Comment by marko-srb** [comment]
@ryelle 

I got a green light from @eidolonnight that this page can go live. 

Draft: 
https://wordpress.org/?page_id=40405&preview=true

Here's the preview of desired styling of the Global navigation (white) and footer (charcoal 2). 
<img width="1280" alt="Creator Connections x2" src="https://github.com/user-attachments/assets/c901975f-cf0e-4fea-8980-82f49c394f4c">

Let me know in case you need any additional input from me... Thanks!

CC: @thetinyl, @ndiego

**Comment by ryelle** [comment]
@eidolonnight @thetinyl Should the URL be `wordpress.org/wordpress-creator-connections` (it is now), or can we drop the duplicate "wordpress" and do `wordpress.org/creator-connections`? No technical requirements here, I just think that looks better.

Once we finalize the URL this can be published, added to the `page-manifest` and synced. If we don't have an answer today, someone else from Neso will need to take over since I'll be AFK.

**Comment by eidolonnight** [comment]
Thanks @ryelle ! I agree that `creator-connections` is cleaner for the URL. Let's go with that.

**Comment by ryelle** [comment]
All published: https://wordpress.org/creator-connections/

It's available for translations, but hasn't been pushed out to Rosetta sites.

I did have to jump in and update the heading levels — the page title is not shown so the first heading in the content should be an `h1`. I reset the font sizes on all the headings to be the same, but it might have impacted some spacing. Just fyi @marko-srb , in case you want to review it again.

**Comment by marko-srb** [comment]
Thanks @ryelle. 

All looks good on desktop. But on mobile we need a few tweaks to make it look ok. 

1. On mobile hero section lacks graphics
2. Last three sections are lacking margin/padding from the sides. 

Let me know if both of these should be easily solvable in the Editor (e.g. adding margins, checking why graphics in hero isn't shown and tweaking the block settings) — and in case yes, I'll take a stab to make the edits and make it work on mobile too. 

Thanks!

**Comment by marko-srb** [comment]
Here are the screenshots:

![Creator-Connections-mobile](https://github.com/user-attachments/assets/62e1c0b5-0277-4bdc-b7eb-732381e50957)

**Comment by ryelle** [comment]
@marko-srb Please open a new issue for any changes, thanks!
