### ISSUE TITLE
Path and Link Broken in Theme Security Handbook

### ISSUE THREAD

**Issue by marcarmengou** [WordPress/wporg-main-2022#435]
In the new WordPress.org translation strings I found a broken link to a section of the Theme Handbook that does not yet exist.

- The link: 

https://github.com/WordPress/wporg-main-2022/blob/618fd76e47510e15fa0184ccd03d52562c1814f0/source/wp-content/themes/wporg-main-2022/patterns/about-security.php#L40

- Theme security path:

From the complete link address `https://developer.wordpress.org/themes/theme-security/theme-security-issues/` the upper section does not exist either `/theme-security/`

**Comment by pkevan** [comment]
hi @marcarmengou, thanks for the report - the pages do exist but aren't in a publicly viewable state at the moment.

I may close this in favour of reporting it upstream to https://github.com/WordPress/wporg-developer/.
