### ISSUE TITLE
About subpages: Site & page title not translatable in local navigation bar

### ISSUE THREAD

**Issue by marcarmengou** [WordPress/wporg-main-2022#436]
The About page (https://wordpress.org/about/) of each locale shows the translated breadcrumbs, but on any subpages `https://wordpress.org/about/*` the breadcrumbs are not translatable.

Translatable: https://ca.wordpress.org/about/
Not translatable: https://ca.wordpress.org/about/security/

![v](https://github.com/WordPress/wporg-main-2022/assets/83702259/e84bfc4d-b081-47b6-9200-18365fd6179a)

**Comment by ryelle** [comment]
Thanks for the issue! These subpages are using the page titles, which are not currently run through translation functions. There's a workaround that only runs on the main About page. Instead, I think we can filter the titles to translate them.

<img width="263" alt="Screenshot 2024-04-25 at 11 05 16 AM" src="https://github.com/WordPress/wporg-main-2022/assets/541093/2ca3eda5-02f5-4bee-9f45-a9faddf18636">
<img width="258" alt="Screenshot 2024-04-25 at 11 05 23 AM" src="https://github.com/WordPress/wporg-main-2022/assets/541093/71c25650-acce-431c-8c83-8e2cbee3e995">
