### ISSUE TITLE
Breadcrumb Navigation bar does Not Appear in Documentation and Support/Forums

### ISSUE THREAD

**Issue by marcarmengou** [WordPress/wporg-main-2022#437]
The breadcrumb next to the logo, in the fixed nav bar, does not appear in the documentation section or in support/forums, but if it appears in News, Patterns and About sections.

![x](https://github.com/WordPress/wporg-main-2022/assets/83702259/d4afa84a-f5a4-492b-92c0-72244be3c014)

### Without breadcrumb 

- https://wordpress.org/documentation/ (appears on subpages, but not in `/documentation/`)
- https://wordpress.org/support/forums/ (appears on subpages, but not in `/support/forums/`)

### With breadcrumb 

- https://wordpress.org/about/
- https://wordpress.org/patterns/

### Without breadcrumb 

- https://es.wordpress.org/support/
- https://es.wordpress.org/support/forums/ (appears on subpages, but not in `/support/forums/`)

### With breadcrumb

- https://es.wordpress.org/news/
- https://es.wordpress.org/patterns/
- https://es.wordpress.org/about/

**Comment by ryelle** [comment]
This local navigation bar has been rolled out to a few sites, but not everywhere yet (as you've found). The progress for that is being tracked in https://github.com/WordPress/wporg-mu-plugins/issues/535

I'm going to close this issue to keep the conversation in one place.
