### ISSUE TITLE
Blocks page: Remove CSS that hides 2nd column on mobile.

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-main-2022#440]
Related to https://github.com/WordPress/wporg-main-2022/pull/438#issuecomment-2109441092

On the mobile breakpoint, the illustration disappears:

![Screenshot 2024-05-14 at 09 05 23](https://github.com/WordPress/wporg-main-2022/assets/1204802/7536f0a3-8682-4270-8c5c-9fac15b794d9)

With the zero bottom margin, it looks a bit tight. There appears to be some custom CSS that hides this:

```
@media (max-width: 781px) {
    #intro .wp-block-column:last-child {
        display: none;
    }
}
```

If we can remove that, it would look like this, which works pretty well:
![Screenshot 2024-05-14 at 09 07 39](https://github.com/WordPress/wporg-main-2022/assets/1204802/26940b15-4997-4540-88c3-c36ec1f45f46)

**Comment by ryelle** [comment]
That CSS is used on the homepage to prevent the brushstroke from wrapping. Instead, let's remove the `intro` ID on this section.
