### ISSUE TITLE
About page: poor wrapping of subheadings, notably in Safari

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-main-2022#442]
There are issues on very wide breakpoints for the https://wordpress.org/about/ page for the headings. This is most notable in Safari:

![Image](https://github.com/WordPress/wporg-main-2022/assets/1204802/83ef0f72-8b3b-44b7-838f-43e29e63b478)

Steps to reproduce:

* Open https://wordpress.org/about/ in Safari
* Have a very wide browser, I'm testing on a 27 inch display. 
* Observe poor text-breaking of the headings.

It is also not ideal in Chrome, but better with less wrapping. 

This is likely a recent regression from changes to how fluid typography works, possibly word-break, site-wide. Suggested solution, set a max-font-size on these headings to 90px.

![Image](https://github.com/WordPress/wporg-main-2022/assets/1204802/448816da-f9d4-448a-b80b-22bb2819541e)

The font size should still ideally be generally fluid, it works well on Mobile. But there needs to be a max font size.

**Comment by adamwoodnz** [comment]
Appears to be due to the `hyphens` setting

![Screenshot 2024-05-24 at 9 21 16 AM](https://github.com/WordPress/wporg-main-2022/assets/1017872/b4094aab-4c4c-4980-9237-ab4fc51648d2)
