### ISSUE TITLE
WCEU Live Stream Hero Banner 

### ISSUE THREAD

**Issue by thetinyl** [WordPress/wporg-main-2022#447]
This banner will replace the banner created in #445 (WCEU small notice banner). It's purpose is to promote the live stream of Matt's presentation at WordCamp Europe 2024. 

### Dates

- **Banner live:** June 15, 2024 anytime before 14:30 UTC
- **Banner update:** June 16 to include a link to the WCEU recap on WordPress/News
- **Remove:** July 19, 2014

### Notes on content and design

- Suggested copy can be found in [this document](https://docs.google.com/document/d/1Le7J173quxhkVYuamdPOE8VtG7wXgjJGLvF68gSyQlA/edit#heading=h.kmyoma5sswzh)
- This iteration of the banner is meant to take over the current "Meet WordPress" hero area (without impacting the H1)
- Design will need to include space for a YouTube embed (@marko-srb perhaps there's a way to integrate the stream's cover image somehow?) 

Happy to answer questions or provide more information if needed.

**Comment by daveloodts** [comment]
I do find the idolization of Matt (and sometimes Josepha) on community channels a bit over the top, if i might say. And i know Matt pays for the whole setup of wordpress.org.
So, i'm fine with it as long as "we" don't forget these events are community-driven. Meaning: also bring awareness about the other awesome talks; link to the channel of wordpress.tv or Youtube. That's only respectful towards the hundreds other volunteers of that event, cause it's not "only" the Matt-show, right.

(by the way: with all due respect for Matt, it's nothing personal. It's for the better good of all volunteers AND the project. Too much focus on 1 person can have an impact on the current volunteering-appetite; that's all i wanting to touch on and worry about it)
