### ISSUE TITLE
Translation issues for launch day?

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-main-2022#46]
Is there anything i18n related that can/must be done for initial launch day?

Probably not, it's all pushed to a later milestone. But let's think it through to be sure.

**Comment by dd32** [comment]
I don't think there's anything technical that needs doing for the initial english launch day.
 - Polyglots need to be informed of the timeline for the Rosetta sites
 - Ensure the new theme doesn't activate on Rosetta sites (it shouldn't, unless we tell it to)

The "WordPress is also available in..." banner is slated to be in the initial launch, and will re-use the existing server-side code, so it should all just be fine. I think.

**Comment by tellyworth** [comment]
Thanks for confirming that Dion!
