### ISSUE TITLE
Remove WCEU 2024 Homepage Banner on July 19

### ISSUE THREAD

**Issue by thetinyl** [WordPress/wporg-main-2022#461]
This is just a reminder that the homepage banner for WCEU 2024 can be taken down on July 19 any time UTC. (See #447 for reference.)  

<img width="1321" alt="image" src="https://github.com/WordPress/wporg-main-2022/assets/100625704/d1a1257f-3abd-4ebc-abc2-4c07fabf009f">

The homepage can then revert back to its previous clean, banner-less self.

**Comment by ryelle** [comment]
I've removed the banner with #483.

**Comment by thetinyl** [comment]
Thanks @ryelle!
