### ISSUE TITLE
Odd underline/link artifact on the user profile > plugins

### ISSUE THREAD

**Issue by richtabor** [WordPress/wporg-main-2022#471]
**Describe the bug**
Noticed this odd underline/link artifact on the user profile view. 

**Screenshots**

![CleanShot 2024-07-13 at 22 39 53](https://github.com/user-attachments/assets/28c5c2ed-98b2-4219-bd72-d6d93905b330)

**Comment by StevenDufresne** [comment]
Thanks for the ticket! This should be fixed now.
