### ISSUE TITLE
Homepage banner: Small notice format for WCUS 2024

### ISSUE THREAD

**Issue by thetinyl** [WordPress/wporg-main-2022#492]
Marketing would like to add a notice banner on the homepage to help promote WordCamp US 2024. The design can be identical to the one used for WordCamp Europe 2024 (see #445 and #446). 

### Dates

- **Go live:** September 4
- **Removed/replaced:** September 18

### Content and copy

Copy:

> See you in Portland: WordCamp US 2024 kicks off on September 17

URL: 
https://wordpress.org/news/2024/09/wordcamp-us-2024-oregon-a-see-you-there/

### Design
As mentioned above, it can be the same notice banner style that was used for WCEU 2024:

![image](https://github.com/user-attachments/assets/886db1f7-d79a-4e6e-b0d2-d3e0feffd8f9)

**Comment by sfougnier** [comment]
We didn't really need a design for this, but I had the mockup handy:

![Fill-wide banner](https://github.com/user-attachments/assets/37617a90-1bab-4585-86aa-e16c561e62b3)

**Comment by thetinyl** [comment]
Thanks @sfougnier! Yep, that looks about right. 

@bmcsherry, any notes here or does this look alright to you?

@ryelle I tried to use one of the patterns that @jasmussen pointed to for the notice banner, but can only seem to find a synced pattern which I can't edit, unfortunately. I can try to recreate the banner in an ugly fashion, but if there's a way to pull the previous one and just edit the text... it'd probably save less time.

**Comment by bjmcsherry** [comment]
@thetinyl That looks great to me. Thank you.

**Comment by thetinyl** [comment]
Confirming that the post this banner will link to has been published: https://wordpress.org/news/2024/09/wordcamp-us-2024-oregon-a-see-you-there/

Note the URL change—I've updated the details above to reflect this. 

@jasmussen FYI. I don't have the right Editor access to port over the [small notice banner design you already put together](https://github.com/WordPress/wporg-main-2022/issues/493#issuecomment-2324254886).

**Comment by jasmussen** [comment]
I went a head and made the update, and the PR is ready, here: https://github.com/WordPress/wporg-main-2022/pull/497#issuecomment-2328211811, I pinged both of you there, Lauren/Kelly. 

It'd be nice if we could give you the right edit access privileges, Lauren!
