### ISSUE TITLE
Update WPCOM copy on Dotorg /hosting page

### ISSUE THREAD

**Issue by sethmclellana8c** [WordPress/wporg-main-2022#498]
We have some updated copy for the WordPress.com listing on the [Dotorg Hosting page](https://href.li/?https://wordpress.org/hosting/). Could someone please update it? Thanks.

NEW
**Get lightning-fast WordPress hosting with full support for your plugins and themes, built by the biggest contributor to WordPress Core. Whether you’re a first-time blogger or an advanced developer, you’ll find all the features you’ll ever need, from intuitive site building and monetization tools, to GitHub deployments, staging sites, WP-CLI, SSH, and more. Scale without stress thanks to unlimited bandwidth, traffic, and visitors—plus 24/7 security.**

Current
At WordPress.com, we’ve built an automatically scalable and secure platform optimized for the latest WordPress has to offer. Start a free website or blog today with everything you need to grow. Get lightning-fast and reliable performance with our global CDN, high-frequency CPUs, multi-datacenter failover, secure login, integrated visitor stats, and more. With managed hosting and the 24/7 support of our dedicated WordPress experts, you’ll be well taken care of.

**Comment by adamwoodnz** [comment]
Deployed

**Comment by sethmclellana8c** [comment]
Thanks for the quick update y'all.
