### ISSUE TITLE
Capabilities: Update "designer" role to access private pages

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-main-2022#499]
Users with "Designer" role (which should be all designers/content editors, but some have higher permissions) cannot currently edit "Private" pages. Initially this was intentional, since using private pages was not expected, but they are being used so this is necessary.

_Originally reported by @jasmussen & @thetinyl in https://github.com/WordPress/wporg-main-2022/issues/493#issuecomment-2337259624_

**Comment by thetinyl** [comment]
Thanks Kelly! Would I need to log out and back in to see if this worked? I'm still getting a "Sorry, you are not allowed to edit this item." when I try to navigate to the [banners test](https://wordpress.org/wp-admin/post.php?post=17559&action=edit) page (as an example).

**Comment by ryelle** [comment]
It was still deploying, but it just finished, so you _should_  be set now.

**Comment by thetinyl** [comment]
Whoops. I was impatient I guess. I see it now! Thanks!
