### ISSUE TITLE
Creator Connections: Padding missing on mobile

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/wporg-main-2022#502]
### Comment

Not sure if this is the right way to submit this bug, but just wanted to inform you that on the new Creator Connections Page the padding is missing on mobile.
<img width="612" alt="CleanShot 2024-09-24 at 08 29 29@2x" src="https://github.com/user-attachments/assets/1e7bdac2-8d8a-48e1-8dce-ff66452aff2c">

**Comment by ndiego** [comment]
I fixed this by adding padding to the blocks in the Editor. Just waiting on the PR to be autogenerated and then I will link it here.

**Comment by ryelle** [comment]
This was fixed with #501
