### ISSUE TITLE
Improve the print stylesheet throughout WordPress.org

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-main-2022#503]
The print styles throughout WordPress.org (the sections powered by the main theme) are pretty rough. It would be worthwhile to make some subtle improvements, much like https://github.com/WordPress/wporg-news-2021/issues/427

In terms of priority, I would focus first on the [About](https://wordpress.org/about/) section. My hunch is the content on these pages is the most likely to be printed.

**Comment by ryelle** [comment]
This is possibly something we should do in the parent theme, so it cascades to all the sections.

**Comment by ndiego** [comment]
> This is possibly something we should do in the parent theme, so it cascades to all the sections.

Ah ok. I will open an issue in https://github.com/WordPress/wporg-parent-2021 and close this one.
