### ISSUE TITLE
Website updates for WordPress 6.7

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-main-2022#507]
This issue is related to #506, but will encompass additional elements of the site that need to be updated alongside the Microsite.

- [x] Homepage "See what's new" blurb (WIP [mockup](https://www.figma.com/design/7awIY9a3ZjBNf0WSmCPzQ2/6.7-Highlight-Grid%2C-Microsite%2C-About-Page?node-id=723-13283&node-type=canvas&t=eUj28xHRjlNdQMXe-0))
- [x] Button link to microsite on [Blocks](https://wordpress.org/blocks/) landing page

I will add additional info here as work progresses.

**Comment by ryelle** [comment]
> Button link to microsite on [Blocks](https://wordpress.org/blocks/) landing page

This link is using a shortcode, so it will update automatically when the release is out  ✅ 

> Homepage "See what's new" blurb

I've added Block Visibility, so I think you could do this with the "Hide block" toggle— the new content (blurb and any new alt text) needs to be saved on the page so that it can run through the translations, but of course it shouldn't be visible until the release is launched. (I suggest "hide block" instead of the date-based option since we don't know exactly when the release will be, but it will require another update & deploy on launch day)

**Comment by ndiego** [comment]
This my first pass at the homepage blurb ([Figma](https://www.figma.com/design/7awIY9a3ZjBNf0WSmCPzQ2/6.7-Highlight-Grid%2C-Microsite%2C-About-Page?node-id=2267-29726&node-type=frame&t=V2AnoYPvKPqKAZaU-0)), but it needs some design help @jasmussen 😅 The main thing to focus on is the text, since that needs to be finalized by the end of the week. 

![Image](https://github.com/user-attachments/assets/1398dadf-3310-4bac-83d4-f5685a2a09bc)

**Comment by jasmussen** [comment]
Nice!

Two quick remixes:

![Image](https://github.com/user-attachments/assets/bf5edc3f-a7e1-4ae0-9035-359abccbc5a0)

![Image](https://github.com/user-attachments/assets/dd33a99d-b55e-4370-b46e-be2cdda3619d)

**Comment by ndiego** [comment]
Looks great. I think I like the one with the dark background on the "Publish" image, but defer to @WordPress/meta-design. 

I added this to the homepage to see what it would look like all put together: 

![Image](https://github.com/user-attachments/assets/74bee393-1c4f-470c-90ed-59532c120fea)

**Comment by jasmussen** [comment]
As the only dark thing in that row, I may be slightly leaning towards the light one. But not at all a strong opinion.

**Comment by ndiego** [comment]
Sounds good, here's the updated version. It does feel more balanced. @ryelle, I have saved this content on the page and hidden it with BV in case you see the autogenerated PR come through. 

![Image](https://github.com/user-attachments/assets/4bfad3ed-5277-4a6f-810c-a3206ad9011b)

**Comment by ndiego** [comment]
FYI @ryelle: I just double-checked the updates, and it looks like I missed the alt text on the "Extend" image. I updated this, and it should be [reflected in the PR](https://github.com/WordPress/wporg-main-2022/pull/508) soon.

**Comment by ryelle** [comment]
I've merged the updated content, and as expected there's no change to the production homepage 👍🏻 

This issue can stay open until 6.7 is released, then it'll be closed by swapping out the new "Core & Features" section.

**Comment by ryelle** [comment]
Homepage update has been deployed, closing this issue.
