### ISSUE TITLE
Lack of line height in titles on Chinese website's release page.

### ISSUE THREAD

**Issue by devhaozi** [WordPress/wporg-main-2022#511]
**Describe the bug**
Lack of line height in titles on Chinese website's release page.

**To Reproduce**
[https://cn.wordpress.org/download/releases/6-6/](https://cn.wordpress.org/download/releases/6-6/)
[https://cn.wordpress.org/download/releases/6-5/](https://cn.wordpress.org/download/releases/6-5/)
[https://cn.wordpress.org/download/releases/6-4/](https://cn.wordpress.org/download/releases/6-4/)

**Expected behavior**
Set `line-height` to 1.2.

**Screenshots**
![Image](https://github.com/user-attachments/assets/c15edc99-60e3-4d85-8849-2f8b76821064)
![Image](https://github.com/user-attachments/assets/f5f98d63-9e16-4e5b-bfee-7c55c35fdb28)
![Image](https://github.com/user-attachments/assets/de011941-5156-4e6d-b174-e605450857bd)

After setting `line-height` to 1.2.

![Image](https://github.com/user-attachments/assets/d20ec6ac-9bed-4a64-889b-4c3e89b0c110)
![Image](https://github.com/user-attachments/assets/7802b6bd-cefd-469e-a3b1-e999abcedce9)
![Image](https://github.com/user-attachments/assets/c3e937f5-3e67-4591-964a-55b4fd4f1378)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version 132

**Additional context**

**Comment by ryelle** [comment]
This had been working, we have a rule that should apply when the html has the attribute `lang="zh-CN"` (see https://github.com/WordPress/wporg-main-2022/issues/424), but the attribute appears to be `lang="zh-Hans"` now. Do you happen to know what changed?

![Image](https://github.com/user-attachments/assets/43833eab-5dbe-400a-8794-66d69a8f90f5)

**Comment by devhaozi** [comment]
> This had been working, we have a rule that should apply when the html has the attribute `lang="zh-CN"` (see [#424](https://github.com/WordPress/wporg-main-2022/issues/424)), but the attribute appears to be `lang="zh-Hans"` now. Do you happen to know what changed?
> 
> ![Image](https://github.com/user-attachments/assets/43833eab-5dbe-400a-8794-66d69a8f90f5)

If this is the case, the HTML lang tag for Chinese (China) was changed some time ago to match the correct bcp47 tag name.

See https://www.ietf.org/rfc/bcp/bcp47.txt

**Comment by ryelle** [comment]
I've deployed the fix for this, though I'm still curious how & when the change was made from `zh-CN` to `zh-Hans` 🤔  Just in case it changes back, I've left the CSS selector `[lang="zh-CN"]` in place.
