### ISSUE TITLE
[SOTW] State of the Word 2024

### ISSUE THREAD

**Issue by marko-srb** [WordPress/wporg-main-2022#517]
Hello, 

Can we do the following edits to the https://wordpress.org/state-of-the-word/ ?

I have made all the edits on the page, except a few one that require dev help.
Here's a draft of the same page: https://wordpress.org/wp-admin/post.php?post=23184&action=edit

Things I need help with are:
- can we put global navigation in light mode?
- can we revert to default blueberry links for this page too? All links
- I also have some optimization issues with the cover/hero image — it keeps getting pixelated and I am not sure what's the issue. Will continue figuring it out
- I also need the admin to update the thumbnail image (attached) as I don't have permission

———

Let me know how I can help further with the edits, or if/and when the above updates can happen.

Thanks a lot.

CC: @ryelle, @sfougnier should I ping someone else?

For visual reference I added screenshot from the draft below (of course it needs light global navigation and links in blueberry).

![Image](https://github.com/user-attachments/assets/a4c1be6c-26e4-4ad5-acd0-8c8ff53ab46b)

**Comment by marko-srb** [comment]
Thumbnail image here.

![Image](https://github.com/user-attachments/assets/a9b43991-eb30-4732-9682-92d62a50abc0)

**Comment by ryelle** [comment]
> can we put global navigation in light mode?
> can we revert to default blueberry links for this page too? All links

Yep, no problem. I'll deploy this shortly.

> I also have some optimization issues with the cover/hero image — it keeps getting pixelated and I am not sure what's the issue. Will continue figuring it out

You mentioned this is a 6.7 issue, but I also wanted to flag that this image is over 1.2MB large, and 7600px wide. This is _very_ large, and will download for everyone (even on mobile). I would typically go with an image of around 3200px wide, which would be 2x retina on most laptop screens, and 4x retina on mobile. The outlier would be anyone full-screening on large monitors, but it's a trade-off for better performance.

> I also need the admin to update the thumbnail image (attached) as I don't have permission

Can you confirm this has already been uploaded, that this is the same image you need? https://wordpress.org/files/2024/11/sotw-2024-landing-thumbnail.jpg

**Comment by marko-srb** [comment]
> You mentioned this is a 6.7 issue, but I also wanted to flag that this image is over 1.2MB large, and 7600px wide. This is very large, and will download for everyone (even on mobile). I would typically go with an image of around 3200px wide, which would be 2x retina on most laptop screens, and 4x retina on mobile. The outlier would be anyone full-screening on large monitors, but it's a trade-off for better performance.

Yes, this is a mistake. I was trying to upload larger to see if issue is still present, will upload now half the size. Apologies. Done.

—

> Can you confirm this has already been uploaded, that this is the same image you need? https://wordpress.org/files/2024/11/sotw-2024-landing-thumbnail.jpg

That indeed is the image we need for thumbnail, however it's not uploaded yet. Here's the screenshot of the current situation.
![Image](https://github.com/user-attachments/assets/8e054646-73f3-4733-8a34-569f364c2b54)

—

Let me know if anything else. Thank you!

**Comment by ryelle** [comment]
Okay, the link color and white header have been deployed, along with the content update for the smaller image, that looks to be a much better size. I've also attached the featured image. Is that everything?

**Comment by marko-srb** [comment]
amazing @ryelle that's all.

Thanks a ton!

**Comment by ryelle** [comment]
Great! I'm going to close this, and if anything else comes up you can open a new issue.
