### ISSUE TITLE
WP.org SOTW Banner Bottom Border

### ISSUE THREAD

**Issue by sfougnier** [WordPress/wporg-main-2022#520]
**Describe the bug**
When going to WP.org homepage, the SOTW banner appears to have a lighter color bottom border than the rest of the horizontal rules on the WP.org site. 

**To Reproduce**
1. Go to wordpress.org homepage
2. See the bottom border color on the global navigation.
3. Compare that to the bottom border on the SOTW banner.
4. Note the color difference.

**Expected behavior**
The bottom border should match the horizontal rules globally on the rest of the dotorg site. It looks like the correct color is #d9d9d9.

**Screenshots**
![Image](https://github.com/user-attachments/assets/ae97520e-067f-4e2d-a080-943641ef970f)

**Comment by ryelle** [comment]
@sfougnier You were added to the site the other day, so you should have access to fix this. When logged in, you can see the "Edit Page" link in the admin bar. Then you can change the border color on that block to "Light grey" which should be #d9d9d9. Typically that'll open a PR to sync the changes, and you would leave a note there, but there's already a pending PR https://github.com/WordPress/wporg-main-2022/pull/518 so just let me know when this is done and I can deploy your change separately.

This also applies for #519, if that can be fixed through the editor.

**Comment by sfougnier** [comment]
@ryelle Sorry about that! I wasn't sure about the protocol. I just updated both in the editor!

**Comment by ryelle** [comment]
Thanks! I've merged the changes and will deploy shortly 🙂
