### ISSUE TITLE
Translate the pop-up window of the download page on rosetta site

### ISSUE THREAD

**Issue by devhaozi** [WordPress/wporg-main-2022#521]
**Describe the bug**
The pop-up content on the rosetta site download page is not translated.

**To Reproduce**
1. Go to [https://cn.wordpress.org/download/](https://cn.wordpress.org/download/)
2. Click on '下载 WordPress 6.7.1'
3. See the untranslated pop-up window

**Expected behavior**
The content of the pop-up window can be translated through the glotpress meta project.

**Screenshots**
![Image](https://github.com/user-attachments/assets/d47f8b2c-bdb1-4afe-b13e-220dbca52ea7)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 132

**Additional context**
none.

**Comment by ryelle** [comment]
This modal _should_ be translated, the content is using [the translation wrapper functions](https://github.com/WordPress/wporg-main-2022/blob/trunk/source/wp-content/themes/wporg-main-2022/src/components/download-modal/download-modal.js), and the strings are in GlotPress, but the translations are not loading.

It's possible loading the translations is a quick fix, but another option would be to refactor the code into a PHP-rendered block using the interactivity API, which would also cut down on the JS loaded on this page.

**Comment by ryelle** [comment]
This has been updated to use a modal block, so the content should be available for translating once GlotPress syncs.
