### ISSUE TITLE
Editing safety in production

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-main-2022#55]
Once the site is launched, anyone editing the front page will face a situation where they can't preview their changes or save a draft, because the page is already published. Effectively they're editing "live".

How can we make that a safer environment?

Some possibilities:
* Lock the publish button and require some special process for changing the content. 
* Use the https://github.com/WordPress/revisions-extended plugin
* Use some other workflow plugin
* ..?

One actionable step would be to test out revisions-extended and see if it works and is suitable.

Other ideas?

**Comment by dd32** [comment]
Another option would be a staging site, that way edits and testing can be made before publishing/pushing to the main site.

That might not be as desirable as it then requires tooling to push changes from staging to production, but that's the general way other large sites would handle content edits I think?

**Comment by ocean90** [comment]
Similar to Revisions Extended is the Rewrite and Republish feature from [Duplicate Post](https://wordpress.org/plugins/duplicate-post/).

**Comment by tellyworth** [comment]
As a crude option: what if we had two "front page" pages, identical copies. One is set to the front page, the other is private.

When updating the page, you edit the private "staging" post. Preview that, make sure all is good. Then copy your edits to the live post.

In an emergency, you could make the private post public and switch it to the front page, while you recover the other.

This is far from perfect but requires no code, and would give us time to find a better workflow solution..

**Comment by dd32** [comment]
Given the changes in #64, this isn't as urgent now, although maybe a staging site whose edits can be pushed to the static templates would be a reasonable edit flow.

**Comment by tellyworth** [comment]
Yep I think that's the way to go. And could turn out to be a really useful workflow. Something like:

* We set up a staging site, or a special plugin on the main site.
* Make sure the post content is a current copy of the patterns.
* Copy and design edits are made on that site, with preview to confirm that it looks right in-situ.
* When edits are ready, we use `yarn setup:refresh` to fetch the latest copy.
* A new script(?) `yarn build:patterns` generates updated pattern files.
* Open a PR, merge, and deploy to publish.

That ensures all published content remains in version control, and gives a safe process for publishing.

The `build:patterns` script could do some pre-processing on the post content: rewrite URLs and post IDs to match the production site; extract translateable strings; generate translated versions of the patterns.

Handling translation "offline" in that way might help simplify #15. It's probably pretty straightforward to have Rosetta sites serve up the translated pattern files where they exist, or fall back to something sensible where they don't (the old theme page?).

**Comment by tellyworth** [comment]
Now that #100 is merged, how do we get this into practical use? We could:

1. Have a staging site (main-test or a new one). That makes some things easier and safer, but would require syncing media files to prod. We could hard-code additions to the [silent theme switcher 
](https://github.com/WordPress/wporg-main-2022/blob/trunk/source/wp-content/mu-plugins/theme-switcher.php) to enable editing/previewing of post content for new page designs and for edits to the existing two pages.
2. Use prod itself, with a plugin so that only editors can see the post content. Add some code to `theme-switcher.php` to make post content selectively visible to editors as they create and edit new page designs while still serving old content (old theme or new theme w/pattern file) to public visitors.

Other ideas? @dd32 which of these sounds like the path of least resistance? Staging is clearly safer but syncing media files isn't without its problems and risks.

**Comment by ryelle** [comment]
@tellyworth this issue was closed automatically because I attached it to #119, so I just wanted to confirm if that should be the case. Does anything else need to happen here?
