### ISSUE TITLE
WP.org Styles: Minor visual improvements

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-main-2022#57]
These two issues are not critical for the launch of the Home and Download pages but I'm flagging them here so we can address them eventually. These were the only things I noticed at this point, everything else is looking great.

**Paragraphs**

On the test site the paragraphs are showing a `30px` line height for me, which is correct for long blocks of text (such as blog posts and eventually other pages of the site with long texts). For smaller pieces of text, which is the case of these pages, the line height should be the one specified in the [Design Library](https://www.figma.com/file/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library).

<img width="1070" alt="Captura de ecrã 2022-08-05, às 16 36 41" src="https://user-images.githubusercontent.com/65220155/183111767-dbb9fbbb-48c1-4f41-bb85-cb8e94600c16.png">

**Buttons**

Buttons are showing up for me with a `66px` height. They should be `50px` on desktop and `64px` on mobile. Specifications [here](https://www.figma.com/file/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?node-id=194%3A530).
<img width="606" alt="Captura de ecrã 2022-08-05, às 15 55 17" src="https://user-images.githubusercontent.com/65220155/183110060-e29e8a4a-b682-4aaf-b90f-2e7d128dfec3.png">

**Comment by ryelle** [comment]
> On the test site the paragraphs are showing a 30px line height for me, which is correct for long blocks of text (such as blog posts and eventually other pages of the site with long texts). For smaller pieces of text, which is the case of these pages, the line height should be the one specified in the [Design Library](https://www.figma.com/file/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library).

I don't think there's an easy way to do this… we can only set one default line height in `theme.json`. Each paragraph's line-height could be customized in the editor? Or we could add a block style to paragraphs for "short text", but that'll also need to be swapped for all paragraphs that need it. Which do you think would be better @beafialho ?

Re buttons — the padding is correct, but the line height needs to be adjusted - it should be `1`.

**Comment by adamwoodnz** [comment]
> On the test site the paragraphs are showing a 30px line height for me, which is correct for long blocks of text (such as blog posts and eventually other pages of the site with long texts). For smaller pieces of text, which is the case of these pages, the line height should be the one specified in the [Design Library](https://www.figma.com/file/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library).

This reads to me like these small texts are the exception and the default should be 30px as currently set. I'll add a small text paragraph option to my PR for feedback, just to get something rolling while we wait for a response.

**Comment by beafialho** [comment]
> Each paragraph's line-height could be customized in the editor? Or we could add a block style to paragraphs for "short text", but that'll also need to be swapped for all paragraphs that need it. Which do you think would be better @beafialho ?

I think it's definitely better to use a block style for short text (do you think this term is intuitive? I'm afraid it can be mistaken by small text which has a smaller font size). Having that block style define would help avoid having several different line heights by mistake while editing.

**Comment by ryelle** [comment]
I think it's understandable enough, I wouldn't confuse it with "small" personally, but we can change the display name later if it's confusing.

> Having that block style define would help avoid having several different line heights by mistake while editing.

Good point 👍🏻

**Comment by ryelle** [comment]
These fixes have been deployed to the `main-test` site, and I've applied the new short-text block style to all the paragraphs. @beafialho how's it look now?

**Comment by beafialho** [comment]
It looks perfect @ryelle, thanks!
