### ISSUE TITLE
Launch day tasks

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-main-2022#63]
What exactly needs to be done in order to launch the site?

- [x] Import all media files from main-test to the real site
- [x] Update patterns to use the local media files & IDs
- [x] Deploy the 2022-theme-switcher.php plugin, activated on the main site
- [x] (maybe) Merge #72
- [x] (maybe) Merge #75
- [x] Merge #81 
- [x] Launch: activate the block theme.

**Comment by tellyworth** [comment]
I think this will work to import all the files:

`wp --url=wordpress.org media import --post_id=POSTID wp-content/blogs.dir/721/files/2022/0*/*`

..where POSTID is the ID of the new Front Page.

**Comment by tellyworth** [comment]
Launching the new theme to the public is a simple matter of activating the block theme in wp-admin on the main site.

**Comment by ryelle** [comment]
Launched ✅  🎉
