### ISSUE TITLE
Update the embed image on the homepage

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-main-2022#70]
Currently this is hardcoded to be an image that exists on the current site, but won't exist on the new page. This should be updated to some other image.

![](https://s.w.org/images/home/screen-themes.png?3)

https://github.com/WordPress/wporg-main-2022/blob/9b4e4f3e1e142645499a411d20b15601a4bd11e9/source/wp-content/themes/wporg-main-2022/inc/page-meta-descriptions.php#L44

cc @critterverse @javierarce @beafialho

**Comment by beafialho** [comment]
Here it is @ryelle. It's in the [Figma file](https://www.figma.com/file/WHhRwVc4swYnPKdyVWj3du/Home-%26-Download-Pages?node-id=1672%3A18514) too.

![wporg_embed_image](https://user-images.githubusercontent.com/65220155/184329441-e632bd05-89c2-492c-8df8-4f752c544bf5.png)
