### ISSUE TITLE
Content is not centered when browser doesn't support CSS4 selectors.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-main-2022#78]
**Describe the bug**
Similar to issue we saw with the navigation, the `group` block also uses `:where` and `:not`.

**For Example:**
When this is missing, the content is not centered.
```
.wp-block-group.wp-container-46 > :where(:not(.alignleft):not(.alignright):not(.alignfull))
```

### Example
**OS**: Catalina
**Safari**: 13.1

<img width="1704" alt="Screen Shot 2022-08-14 at 7 32 54 PM" src="https://user-images.githubusercontent.com/1657336/184532981-b76f6046-47f0-4d4b-93eb-b39e8d77aed7.png">

**Comment by iandunn** [comment]
reference for the previous time this happened

* [local issue](https://github.com/WordPress/wporg-mu-plugins/issues/159)
* [local workaround](https://github.com/WordPress/wporg-mu-plugins/pull/178)
* [upstream issue](https://github.com/WordPress/gutenberg/issues/39230)
* [upstream discussion](https://github.com/WordPress/gutenberg/discussions/39621)
* [upstream fix](https://github.com/WordPress/gutenberg/pull/42967)

**Comment by iandunn** [comment]
I opened [an upstream issue](https://github.com/WordPress/gutenberg/issues/43723) for this, to fix the root cause. In the mean time I'll add a workaround.
