### ISSUE TITLE
Pattern: Download button

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-main-2022#8]
Do we need a custom block for the download button, or can it be a regular button block?

Is it a static link (always `https://wordpress.org/latest.zip`) or do we need to add the version/timestamp/SHA/etc to it? In `wporg-main`, the URL is dynamic, but that's because it can be updated to point to the locale-specific build.

Current mockup:

<img width="597" alt="Screen Shot 2022-07-20 at 4 38 44 PM" src="https://user-images.githubusercontent.com/541093/180077234-d31e1903-4083-4e8d-abc7-6c749bec53fd.png">

**Comment by dd32** [comment]
It seems like the immediate needs here can be solved by a shortcode, rather than a custom block. See #10 + #27.

A custom pre-defined button block with the shortcodes (and later tokens) wouldn't be out of the question though to simplify the editing experience.

**Comment by ryelle** [comment]
I think we could create a pattern that uses the shortcodes, rather than a custom block, so editors can just drop the pattern in place.

**Comment by ryelle** [comment]
Closing in favor of the eventual download modal block #52
