### ISSUE TITLE
Block: Randomized hosts

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-main-2022#9]
⚠️  This design is not final, we might show all hosts and if so, wouldn't need a random block.

On [the live page](https://wordpress.org/download/), there are 2 hosts displayed but these shuffle between 4 possible hosts.

Each host has a name, description, logo, and URL. The logo is not currently used in this mockup.

Current mockup:

<img width="1186" alt="Screen Shot 2022-07-20 at 4 48 28 PM" src="https://user-images.githubusercontent.com/541093/180079008-badcbecc-9ca9-46f2-b60b-f83c45c092c9.png">

**Comment by dd32** [comment]
The [latest mockup](https://make.wordpress.org/design/2022/07/27/project-update-wordpress-org-homepage-and-download-page-mockups/) has removed the individual Hosts callouts from the Downloads page, and replaced it with a link to the Hosting page instead.

Seems like this block can be left until the Hosting page gets a refresh.
