### ISSUE TITLE
Add missing links to the download page

### ISSUE THREAD

**Issue by javierarce** [WordPress/wporg-main-2022#94]
We forgot linking to several important pages from the download page:

- https://wordpress.org/download/releases
- https://wordpress.org/download/beta-nightly
- https://wordpress.org/download/counter
- https://wordpress.org/download/source

We've updated [the designs](https://www.figma.com/file/WHhRwVc4swYnPKdyVWj3du/Home-%26-Download-Pages?node-id=970%3A9767) to add them under the download links

![image](https://user-images.githubusercontent.com/4933/185091060-777af6d2-19e6-4805-af77-32cec7e277b1.png)

**Comment by ryelle** [comment]
@javierarce Right now, we can't easily change the font size of this from desktop to mobile — should it be 12px or 14px? Or should we update the small text behavior to switch to 14px on small screens?

**Comment by javierarce** [comment]
Let's go with 14px for both then, since 12px is too small for mobile.

> Or should we update the small text behavior to switch to 14px on small screens? 

I think this won't be necessary, but pinging @beafialho in case she feels the links are too big on the desktop and we need to adjust it.

**Comment by beafialho** [comment]
> Let's go with 14px for both then, since 12px is too small for mobile.
> 
> > Or should we update the small text behavior to switch to 14px on small screens?
> 
> I think this won't be necessary, but pinging @beafialho in case, she feels the links are too big on the desktop, and we need to adjust it.

I agree, let's go with 14px.

**Comment by ryelle** [comment]
Reopening because I missed the little spacer dots.
