### ISSUE TITLE
Consider compressing the community image

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-main-2022#97]
**Describe the bug**

`community-photo-2.webp` is 738kb, which is quite large especially for a monochrome image. I think it was probably saved with lossless compression. This is by far the biggest asset loaded on the page.

We could improve performance with minimal visible differences by using lossy compression. Here's a quick before/after created using `cwebp`:

### community-photo-2.webp original, 738kb
![community-photo-2.webp](https://wordpress.org/files/2022/08/community-photo-2.webp)
`https://wordpress.org/files/2022/08/community-photo-2.webp`

### community-photo-2-q50.webp compressed at quality=50, 263kb
![community-photo-2-q50.webp](https://wordpress.org/files/2022/08/community-photo-2-q50.webp)
`https://wordpress.org/files/2022/08/community-photo-2-q50.webp`

(You may need to compare using those direct URLs to bypass further compression introduced by GitHub)

That's about a 64% reduction in file size. I think alpha is correctly preserved. I tried progressively lower qualities till I could (barely) start to see a difference, that's how I settled on q50. We could probably make it smaller still depending on design review.

Compression was with these parameters, for reference:

`cwebp community-photo-2.webp -q 50 -alpha_q 100 -m 6 -o community-photo-2-q50.webp`

**Comment by tellyworth** [comment]
Related: #89, #90.

**Comment by jasmussen** [comment]
Nice, and just wanted to confirm that the gray color in [the compressed version](https://wordpress.org/files/2022/08/community-photo-2-q50.webp) is correct, so seems safe to swap out!

**Comment by adamwoodnz** [comment]
I've tried targeting 200kb using the `-size` option and it isn't too much more degraded, but I think I agree that your quality `50` result seems like the sweet spot. I'll put up a PR for that.
