### ISSUE TITLE
Remove page-patterns from the editor Pattern tab

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-main-2022#98]
Currently, the page patterns (Download & Front Page) are registered as patterns that can be used on the site. This is confusing, because you can put, for example, the download content on any random page. These aren't patterns in the traditional sense, so they should be removed from the user's view.

<img width="345" alt="Screen Shot 2022-08-19 at 1 25 08 PM" src="https://user-images.githubusercontent.com/541093/185674276-bd815028-cedf-489a-9b7f-54a850414231.png">

**Comment by tellyworth** [comment]
Does it still make sense for the content to live in pattern files specifically? Is the solution to move them into something else like template files instead?

**Comment by ryelle** [comment]
I guess we could write directly to the template files… or template parts if we want to keep the post content separate from the header & footer. Would that affect translation at all?

**Comment by ryelle** [comment]
We can just add `Inserter: no` to the header. See https://github.com/WordPress/WordPress/blob/b01bafe003031285c649004d097cdec4c58642e7/wp-includes/block-patterns.php#L185-L192 & https://github.com/WordPress/twentytwentythree/blob/trunk/patterns/hidden-404.php
